create table NEW_TABLE (
	id INT,
	first_name VARCHAR(50),
	app_name VARCHAR(50)
);
insert into NEW_TABLE (id, first_name, app_name) values (1, 'Bandicoot, long-nosed', 'Tampflex');
insert into NEW_TABLE (id, first_name, app_name) values (2, 'Pelican, eastern white', 'Solarbreeze');
insert into NEW_TABLE (id, first_name, app_name) values (3, 'Cottonmouth', 'Fintone');
insert into NEW_TABLE (id, first_name, app_name) values (4, 'Bat, little brown', 'Sub-Ex');
insert into NEW_TABLE (id, first_name, app_name) values (5, 'Rufous-collared sparrow', 'Matsoft');
insert into NEW_TABLE (id, first_name, app_name) values (6, 'Burmese black mountain tortoise', 'Daltfresh');
insert into NEW_TABLE (id, first_name, app_name) values (7, 'Whale, long-finned pilot', 'Aerified');
insert into NEW_TABLE (id, first_name, app_name) values (8, 'Eleven-banded armadillo (unidentified)', 'Fixflex');
insert into NEW_TABLE (id, first_name, app_name) values (9, 'Steller sea lion', 'Temp');
insert into NEW_TABLE (id, first_name, app_name) values (10, 'Tree porcupine', 'Vagram');
insert into NEW_TABLE (id, first_name, app_name) values (11, 'African fish eagle', 'Biodex');
insert into NEW_TABLE (id, first_name, app_name) values (12, 'Peacock, blue', 'Redhold');
insert into NEW_TABLE (id, first_name, app_name) values (13, 'Weaver, red-billed buffalo', 'Y-Solowarm');
insert into NEW_TABLE (id, first_name, app_name) values (14, 'Topi', 'Subin');
insert into NEW_TABLE (id, first_name, app_name) values (15, 'Eagle, pallas''s fish', 'Bamity');
insert into NEW_TABLE (id, first_name, app_name) values (16, 'Possum, common brushtail', 'Toughjoyfax');
insert into NEW_TABLE (id, first_name, app_name) values (17, 'Dove, mourning collared', 'Holdlamis');
insert into NEW_TABLE (id, first_name, app_name) values (18, 'Brush-tailed bettong', 'Kanlam');
insert into NEW_TABLE (id, first_name, app_name) values (19, 'Possum, western pygmy', 'Tampflex');
insert into NEW_TABLE (id, first_name, app_name) values (20, 'Olive baboon', 'Voltsillam');
insert into NEW_TABLE (id, first_name, app_name) values (21, 'Ring-necked pheasant', 'Fix San');
insert into NEW_TABLE (id, first_name, app_name) values (22, 'Turtle, eastern box', 'Aerified');
insert into NEW_TABLE (id, first_name, app_name) values (23, 'Chimpanzee', 'Solarbreeze');
insert into NEW_TABLE (id, first_name, app_name) values (24, 'Stork, greater adjutant', 'Fixflex');
insert into NEW_TABLE (id, first_name, app_name) values (25, 'Southern right whale', 'Alphazap');
insert into NEW_TABLE (id, first_name, app_name) values (26, 'European badger', 'Temp');
insert into NEW_TABLE (id, first_name, app_name) values (27, 'Pig-tailed macaque', 'Otcom');
insert into NEW_TABLE (id, first_name, app_name) values (28, 'Mountain duck', 'Ronstring');
insert into NEW_TABLE (id, first_name, app_name) values (29, 'Dik, kirk''s dik', 'Ronstring');
insert into NEW_TABLE (id, first_name, app_name) values (30, 'Stork, yellow-billed', 'Solarbreeze');
insert into NEW_TABLE (id, first_name, app_name) values (31, 'Goose, egyptian', 'Fintone');
insert into NEW_TABLE (id, first_name, app_name) values (32, 'Pigeon, wood', 'Zathin');
insert into NEW_TABLE (id, first_name, app_name) values (33, 'Yellow-billed stork', 'Latlux');
insert into NEW_TABLE (id, first_name, app_name) values (34, 'Mountain lion', 'Regrant');
insert into NEW_TABLE (id, first_name, app_name) values (35, 'European red squirrel', 'Bitchip');
insert into NEW_TABLE (id, first_name, app_name) values (36, 'Scottish highland cow', 'Y-Solowarm');
insert into NEW_TABLE (id, first_name, app_name) values (37, 'Black-capped chickadee', 'Keylex');
insert into NEW_TABLE (id, first_name, app_name) values (38, 'Wapiti, elk,', 'Solarbreeze');
insert into NEW_TABLE (id, first_name, app_name) values (39, 'Skink, african', 'Duobam');
insert into NEW_TABLE (id, first_name, app_name) values (40, 'Black-capped capuchin', 'Tres-Zap');
insert into NEW_TABLE (id, first_name, app_name) values (41, 'Goldeneye, barrows', 'Andalax');
insert into NEW_TABLE (id, first_name, app_name) values (42, 'Caracara, yellow-headed', 'Konklab');
insert into NEW_TABLE (id, first_name, app_name) values (43, 'Egret, great', 'Flowdesk');
insert into NEW_TABLE (id, first_name, app_name) values (44, 'Green-backed heron', 'Flexidy');
insert into NEW_TABLE (id, first_name, app_name) values (45, 'Black-eyed bulbul', 'Ronstring');
insert into NEW_TABLE (id, first_name, app_name) values (46, 'Herring gull', 'Flowdesk');
insert into NEW_TABLE (id, first_name, app_name) values (47, 'Beisa oryx', 'Redhold');
insert into NEW_TABLE (id, first_name, app_name) values (48, 'Dusky rattlesnake', 'Keylex');
insert into NEW_TABLE (id, first_name, app_name) values (49, 'Burmese black mountain tortoise', 'Hatity');
insert into NEW_TABLE (id, first_name, app_name) values (50, 'European badger', 'Domainer');
insert into NEW_TABLE (id, first_name, app_name) values (51, 'Eurasian hoopoe', 'Greenlam');
insert into NEW_TABLE (id, first_name, app_name) values (52, 'Spotted wood sandpiper', 'Latlux');
insert into NEW_TABLE (id, first_name, app_name) values (53, 'Stork, marabou', 'Bitwolf');
insert into NEW_TABLE (id, first_name, app_name) values (54, 'Dassie', 'Zontrax');
insert into NEW_TABLE (id, first_name, app_name) values (55, 'Marmot, hoary', 'Viva');
insert into NEW_TABLE (id, first_name, app_name) values (56, 'Comb duck', 'Veribet');
insert into NEW_TABLE (id, first_name, app_name) values (57, 'Rhea, gray', 'Regrant');
insert into NEW_TABLE (id, first_name, app_name) values (58, 'Blue duck', 'Hatity');
insert into NEW_TABLE (id, first_name, app_name) values (59, 'Australian pelican', 'Cookley');
insert into NEW_TABLE (id, first_name, app_name) values (60, 'Spoonbill, european', 'Tampflex');
insert into NEW_TABLE (id, first_name, app_name) values (61, 'Iguana, common green', 'Hatity');
insert into NEW_TABLE (id, first_name, app_name) values (62, 'Red meerkat', 'Zathin');
insert into NEW_TABLE (id, first_name, app_name) values (63, 'Roseate cockatoo', 'Zamit');
insert into NEW_TABLE (id, first_name, app_name) values (64, 'Striated heron', 'Keylex');
insert into NEW_TABLE (id, first_name, app_name) values (65, 'Blue peacock', 'Prodder');
insert into NEW_TABLE (id, first_name, app_name) values (66, 'Burmese black mountain tortoise', 'Temp');
insert into NEW_TABLE (id, first_name, app_name) values (67, 'Savanna fox', 'Quo Lux');
insert into NEW_TABLE (id, first_name, app_name) values (68, 'Badger, european', 'Zathin');
insert into NEW_TABLE (id, first_name, app_name) values (69, 'Heron, black-crowned night', 'Fixflex');
insert into NEW_TABLE (id, first_name, app_name) values (70, 'Burmese black mountain tortoise', 'Stringtough');
insert into NEW_TABLE (id, first_name, app_name) values (71, 'Weaver, sociable', 'Namfix');
insert into NEW_TABLE (id, first_name, app_name) values (72, 'Sandgrouse, yellow-throated', 'Tempsoft');
insert into NEW_TABLE (id, first_name, app_name) values (73, 'Giant girdled lizard', 'Keylex');
insert into NEW_TABLE (id, first_name, app_name) values (74, 'Chilean flamingo', 'Flexidy');
insert into NEW_TABLE (id, first_name, app_name) values (75, 'Darwin ground finch (unidentified)', 'Lotlux');
insert into NEW_TABLE (id, first_name, app_name) values (76, 'Campo flicker', 'Tresom');
insert into NEW_TABLE (id, first_name, app_name) values (77, 'Galapagos penguin', 'Zamit');
insert into NEW_TABLE (id, first_name, app_name) values (78, 'Beaver, north american', 'Bitwolf');
insert into NEW_TABLE (id, first_name, app_name) values (79, 'Arctic tern', 'Bytecard');
insert into NEW_TABLE (id, first_name, app_name) values (80, 'Kudu, greater', 'Y-Solowarm');
insert into NEW_TABLE (id, first_name, app_name) values (81, 'Kudu, greater', 'Span');
insert into NEW_TABLE (id, first_name, app_name) values (82, 'Lapwing (unidentified)', 'Holdlamis');
insert into NEW_TABLE (id, first_name, app_name) values (83, 'Nubian bee-eater', 'Mat Lam Tam');
insert into NEW_TABLE (id, first_name, app_name) values (84, 'Common genet', 'Vagram');
insert into NEW_TABLE (id, first_name, app_name) values (85, 'European beaver', 'Flowdesk');
insert into NEW_TABLE (id, first_name, app_name) values (86, 'Goose, canada', 'Asoka');
insert into NEW_TABLE (id, first_name, app_name) values (87, 'Blackish oystercatcher', 'Voltsillam');
insert into NEW_TABLE (id, first_name, app_name) values (88, 'Red-headed woodpecker', 'Quo Lux');
insert into NEW_TABLE (id, first_name, app_name) values (89, 'Hartebeest, red', 'Asoka');
insert into NEW_TABLE (id, first_name, app_name) values (90, 'Uinta ground squirrel', 'Bitwolf');
insert into NEW_TABLE (id, first_name, app_name) values (91, 'Eagle, crowned', 'Ronstring');
insert into NEW_TABLE (id, first_name, app_name) values (92, 'Common zebra', 'Vagram');
insert into NEW_TABLE (id, first_name, app_name) values (93, 'Cormorant (unidentified)', 'Kanlam');
insert into NEW_TABLE (id, first_name, app_name) values (94, 'White stork', 'Transcof');
insert into NEW_TABLE (id, first_name, app_name) values (95, 'Indian porcupine', 'Stim');
insert into NEW_TABLE (id, first_name, app_name) values (96, 'Hyena, striped', 'Konklux');
insert into NEW_TABLE (id, first_name, app_name) values (97, 'Darwin ground finch (unidentified)', 'Bamity');
insert into NEW_TABLE (id, first_name, app_name) values (98, 'White-headed vulture', 'Sub-Ex');
insert into NEW_TABLE (id, first_name, app_name) values (99, 'Squirrel, richardson''s ground', 'Trippledex');
insert into NEW_TABLE (id, first_name, app_name) values (100, 'Brolga crane', 'Y-find');
insert into NEW_TABLE (id, first_name, app_name) values (101, 'Nighthawk, common', 'Job');
insert into NEW_TABLE (id, first_name, app_name) values (102, 'Australian brush turkey', 'Flexidy');
insert into NEW_TABLE (id, first_name, app_name) values (103, 'Wild water buffalo', 'Matsoft');
insert into NEW_TABLE (id, first_name, app_name) values (104, 'Sacred ibis', 'Subin');
insert into NEW_TABLE (id, first_name, app_name) values (105, 'Duck, white-faced whistling', 'Pannier');
insert into NEW_TABLE (id, first_name, app_name) values (106, 'Bee-eater, carmine', 'Cookley');
insert into NEW_TABLE (id, first_name, app_name) values (107, 'Macaque, japanese', 'Tres-Zap');
insert into NEW_TABLE (id, first_name, app_name) values (108, 'Red-billed toucan', 'Konklab');
insert into NEW_TABLE (id, first_name, app_name) values (109, 'Cockatoo, long-billed', 'Ronstring');
insert into NEW_TABLE (id, first_name, app_name) values (110, 'Boa, malagasy ground', 'Transcof');
insert into NEW_TABLE (id, first_name, app_name) values (111, 'Bird, secretary', 'Otcom');
insert into NEW_TABLE (id, first_name, app_name) values (112, 'Burrowing owl', 'Alphazap');
insert into NEW_TABLE (id, first_name, app_name) values (113, 'Bear, grizzly', 'Tres-Zap');
insert into NEW_TABLE (id, first_name, app_name) values (114, 'Pine squirrel', 'Tresom');
insert into NEW_TABLE (id, first_name, app_name) values (115, 'Woodrat (unidentified)', 'Cookley');
insert into NEW_TABLE (id, first_name, app_name) values (116, 'Kangaroo, red', 'Quo Lux');
insert into NEW_TABLE (id, first_name, app_name) values (117, 'Otter, north american river', 'Home Ing');
insert into NEW_TABLE (id, first_name, app_name) values (118, 'Great white pelican', 'Hatity');
insert into NEW_TABLE (id, first_name, app_name) values (119, 'Gecko, bent-toed', 'Flexidy');
insert into NEW_TABLE (id, first_name, app_name) values (120, 'Duiker, gray', 'Subin');
insert into NEW_TABLE (id, first_name, app_name) values (121, 'Raccoon dog', 'Asoka');
insert into NEW_TABLE (id, first_name, app_name) values (122, 'Southern boubou', 'Solarbreeze');
insert into NEW_TABLE (id, first_name, app_name) values (123, 'American woodcock', 'Regrant');
insert into NEW_TABLE (id, first_name, app_name) values (124, 'Hottentot teal', 'Veribet');
insert into NEW_TABLE (id, first_name, app_name) values (125, 'Common zebra', 'Veribet');
insert into NEW_TABLE (id, first_name, app_name) values (126, 'Praying mantis (unidentified)', 'Matsoft');
insert into NEW_TABLE (id, first_name, app_name) values (127, 'Stork, european', 'Latlux');
insert into NEW_TABLE (id, first_name, app_name) values (128, 'Fisher', 'Tampflex');
insert into NEW_TABLE (id, first_name, app_name) values (129, 'Pale-throated three-toed sloth', 'Rank');
insert into NEW_TABLE (id, first_name, app_name) values (130, 'Monster, gila', 'Duobam');
insert into NEW_TABLE (id, first_name, app_name) values (131, 'Goldeneye, common', 'Overhold');
insert into NEW_TABLE (id, first_name, app_name) values (132, 'Australian spiny anteater', 'Zathin');
insert into NEW_TABLE (id, first_name, app_name) values (133, 'Shrike, crimson-breasted', 'Bamity');
insert into NEW_TABLE (id, first_name, app_name) values (134, 'Black-crowned crane', 'Ronstring');
insert into NEW_TABLE (id, first_name, app_name) values (135, 'Beaver, american', 'Regrant');
insert into NEW_TABLE (id, first_name, app_name) values (136, 'Otter, african clawless', 'Tresom');
insert into NEW_TABLE (id, first_name, app_name) values (137, 'Dove, laughing', 'Cardify');
insert into NEW_TABLE (id, first_name, app_name) values (138, 'Least chipmunk', 'Konklux');
insert into NEW_TABLE (id, first_name, app_name) values (139, 'Gull, swallow-tail', 'Opela');
insert into NEW_TABLE (id, first_name, app_name) values (140, 'Quail, gambel''s', 'Zontrax');
insert into NEW_TABLE (id, first_name, app_name) values (141, 'Yellow mongoose', 'Holdlamis');
insert into NEW_TABLE (id, first_name, app_name) values (142, 'Admiral, indian red', 'Konklux');
insert into NEW_TABLE (id, first_name, app_name) values (143, 'Fisher', 'Greenlam');
insert into NEW_TABLE (id, first_name, app_name) values (144, 'Hawk-eagle, crowned', 'Duobam');
insert into NEW_TABLE (id, first_name, app_name) values (145, 'Monkey, red howler', 'Subin');
insert into NEW_TABLE (id, first_name, app_name) values (146, 'Armadillo, seven-banded', 'Bytecard');
insert into NEW_TABLE (id, first_name, app_name) values (147, 'Kangaroo, western grey', 'Duobam');
insert into NEW_TABLE (id, first_name, app_name) values (148, 'Bee-eater (unidentified)', 'Matsoft');
insert into NEW_TABLE (id, first_name, app_name) values (149, 'Tailless tenrec', 'Trippledex');
insert into NEW_TABLE (id, first_name, app_name) values (150, 'Turkey, wild', 'Cardify');
insert into NEW_TABLE (id, first_name, app_name) values (151, 'Short-nosed bandicoot', 'Greenlam');
insert into NEW_TABLE (id, first_name, app_name) values (152, 'Netted rock dragon', 'Zaam-Dox');
insert into NEW_TABLE (id, first_name, app_name) values (153, 'Seal, northern elephant', 'Otcom');
insert into NEW_TABLE (id, first_name, app_name) values (154, 'Canadian river otter', 'Viva');
insert into NEW_TABLE (id, first_name, app_name) values (155, 'Heron, green', 'Fixflex');
insert into NEW_TABLE (id, first_name, app_name) values (156, 'Flightless cormorant', 'Stronghold');
insert into NEW_TABLE (id, first_name, app_name) values (157, 'Tyrant flycatcher', 'Pannier');
insert into NEW_TABLE (id, first_name, app_name) values (158, 'Pie, indian tree', 'Cookley');
insert into NEW_TABLE (id, first_name, app_name) values (159, 'Lappet-faced vulture', 'Home Ing');
insert into NEW_TABLE (id, first_name, app_name) values (160, 'Frilled dragon', 'Span');
insert into NEW_TABLE (id, first_name, app_name) values (161, 'Giant girdled lizard', 'Trippledex');
insert into NEW_TABLE (id, first_name, app_name) values (162, 'Seal, northern fur', 'Cardguard');
insert into NEW_TABLE (id, first_name, app_name) values (163, 'Wild boar', 'Temp');
insert into NEW_TABLE (id, first_name, app_name) values (164, 'Southern hairy-nosed wombat', 'Bitwolf');
insert into NEW_TABLE (id, first_name, app_name) values (165, 'Carpet python', 'Keylex');
insert into NEW_TABLE (id, first_name, app_name) values (166, 'Vulture, egyptian', 'Fix San');
insert into NEW_TABLE (id, first_name, app_name) values (167, 'White-throated monitor', 'Ventosanzap');
insert into NEW_TABLE (id, first_name, app_name) values (168, 'Snake (unidentified)', 'Bitwolf');
insert into NEW_TABLE (id, first_name, app_name) values (169, 'Brush-tailed bettong', 'Sub-Ex');
insert into NEW_TABLE (id, first_name, app_name) values (170, 'Tailless tenrec', 'Kanlam');
insert into NEW_TABLE (id, first_name, app_name) values (171, 'Bare-faced go away bird', 'Matsoft');
insert into NEW_TABLE (id, first_name, app_name) values (172, 'Mudskipper (unidentified)', 'Bitchip');
insert into NEW_TABLE (id, first_name, app_name) values (173, 'Roan antelope', 'Tempsoft');
insert into NEW_TABLE (id, first_name, app_name) values (174, 'Tawny eagle', 'Alphazap');
insert into NEW_TABLE (id, first_name, app_name) values (175, 'Red deer', 'Regrant');
insert into NEW_TABLE (id, first_name, app_name) values (176, 'Crane, brolga', 'Cookley');
insert into NEW_TABLE (id, first_name, app_name) values (177, 'Woodpecker, downy', 'Stim');
insert into NEW_TABLE (id, first_name, app_name) values (178, 'Blue and gold macaw', 'Aerified');
insert into NEW_TABLE (id, first_name, app_name) values (179, 'Rhinoceros, black', 'Bitwolf');
insert into NEW_TABLE (id, first_name, app_name) values (180, 'Arctic lemming', 'Otcom');
insert into NEW_TABLE (id, first_name, app_name) values (181, 'Little brown dove', 'Y-find');
insert into NEW_TABLE (id, first_name, app_name) values (182, 'Sally lightfoot crab', 'Trippledex');
insert into NEW_TABLE (id, first_name, app_name) values (183, 'Green-winged macaw', 'Cardify');
insert into NEW_TABLE (id, first_name, app_name) values (184, 'Long-crested hawk eagle', 'Bamity');
insert into NEW_TABLE (id, first_name, app_name) values (185, 'Otter, african clawless', 'Alphazap');
insert into NEW_TABLE (id, first_name, app_name) values (186, 'Sage hen', 'Greenlam');
insert into NEW_TABLE (id, first_name, app_name) values (187, 'Wolf, mexican', 'Stronghold');
insert into NEW_TABLE (id, first_name, app_name) values (188, 'Burmese black mountain tortoise', 'Tresom');
insert into NEW_TABLE (id, first_name, app_name) values (189, 'Southern boubou', 'Keylex');
insert into NEW_TABLE (id, first_name, app_name) values (190, 'Indian leopard', 'Ventosanzap');
insert into NEW_TABLE (id, first_name, app_name) values (191, 'Eastern box turtle', 'Hatity');
insert into NEW_TABLE (id, first_name, app_name) values (192, 'Glider, squirrel', 'Bamity');
insert into NEW_TABLE (id, first_name, app_name) values (193, 'Blue and yellow macaw', 'Zontrax');
insert into NEW_TABLE (id, first_name, app_name) values (194, 'Eagle, tawny', 'Flowdesk');
insert into NEW_TABLE (id, first_name, app_name) values (195, 'Boa, columbian rainbow', 'Sonair');
insert into NEW_TABLE (id, first_name, app_name) values (196, 'Egyptian vulture', 'Job');
insert into NEW_TABLE (id, first_name, app_name) values (197, 'Chilean flamingo', 'Biodex');
insert into NEW_TABLE (id, first_name, app_name) values (198, 'American bighorn sheep', 'Fixflex');
insert into NEW_TABLE (id, first_name, app_name) values (199, 'Possum, ring-tailed', 'Alpha');
insert into NEW_TABLE (id, first_name, app_name) values (200, 'Mountain duck', 'Latlux');
insert into NEW_TABLE (id, first_name, app_name) values (201, 'Stork, marabou', 'Home Ing');
insert into NEW_TABLE (id, first_name, app_name) values (202, 'Salmon, sockeye', 'Zontrax');
insert into NEW_TABLE (id, first_name, app_name) values (203, 'Tiger', 'Prodder');
insert into NEW_TABLE (id, first_name, app_name) values (204, 'Mouse, four-striped grass', 'Tin');
insert into NEW_TABLE (id, first_name, app_name) values (205, 'Deer, white-tailed', 'Lotstring');
insert into NEW_TABLE (id, first_name, app_name) values (206, 'Weaver, white-browed sparrow', 'Zamit');
insert into NEW_TABLE (id, first_name, app_name) values (207, 'Common raccoon', 'Treeflex');
insert into NEW_TABLE (id, first_name, app_name) values (208, 'Crane, stanley', 'Zontrax');
insert into NEW_TABLE (id, first_name, app_name) values (209, 'Legaan, Monitor (unidentified)', 'Treeflex');
insert into NEW_TABLE (id, first_name, app_name) values (210, 'Eastern white pelican', 'Alpha');
insert into NEW_TABLE (id, first_name, app_name) values (211, 'Anaconda (unidentified)', 'Tin');
insert into NEW_TABLE (id, first_name, app_name) values (212, 'Comb duck', 'Cookley');
insert into NEW_TABLE (id, first_name, app_name) values (213, 'Bleu, red-cheeked cordon', 'Otcom');
insert into NEW_TABLE (id, first_name, app_name) values (214, 'Pie, rufous tree', 'Zaam-Dox');
insert into NEW_TABLE (id, first_name, app_name) values (215, 'Phalarope, northern', 'Bamity');
insert into NEW_TABLE (id, first_name, app_name) values (216, 'Pelican, australian', 'Tampflex');
insert into NEW_TABLE (id, first_name, app_name) values (217, 'Cereopsis goose', 'Temp');
insert into NEW_TABLE (id, first_name, app_name) values (218, 'Kudu, greater', 'Temp');
insert into NEW_TABLE (id, first_name, app_name) values (219, 'Roller, lilac-breasted', 'Redhold');
insert into NEW_TABLE (id, first_name, app_name) values (220, 'Heron, striated', 'Subin');
insert into NEW_TABLE (id, first_name, app_name) values (221, 'Common zorro', 'Wrapsafe');
insert into NEW_TABLE (id, first_name, app_name) values (222, 'South American meadowlark (unidentified)', 'Konklab');
insert into NEW_TABLE (id, first_name, app_name) values (223, 'Lion, california sea', 'Tres-Zap');
insert into NEW_TABLE (id, first_name, app_name) values (224, 'Little brown dove', 'Cardguard');
insert into NEW_TABLE (id, first_name, app_name) values (225, 'Coqui francolin', 'Zontrax');
insert into NEW_TABLE (id, first_name, app_name) values (226, 'Bee-eater, white-fronted', 'Sub-Ex');
insert into NEW_TABLE (id, first_name, app_name) values (227, 'Mongoose, small indian', 'Viva');
insert into NEW_TABLE (id, first_name, app_name) values (228, 'Pademelon, red-legged', 'Bigtax');
insert into NEW_TABLE (id, first_name, app_name) values (229, 'Dolphin, striped', 'Cardguard');
insert into NEW_TABLE (id, first_name, app_name) values (230, 'Madagascar hawk owl', 'Gembucket');
insert into NEW_TABLE (id, first_name, app_name) values (231, 'Indian peacock', 'Zontrax');
insert into NEW_TABLE (id, first_name, app_name) values (232, 'Antelope, sable', 'Holdlamis');
insert into NEW_TABLE (id, first_name, app_name) values (233, 'Eurasian badger', 'Overhold');
insert into NEW_TABLE (id, first_name, app_name) values (234, 'Curve-billed thrasher', 'Job');
insert into NEW_TABLE (id, first_name, app_name) values (235, 'Vulture, lappet-faced', 'Solarbreeze');
insert into NEW_TABLE (id, first_name, app_name) values (236, 'Crab, sally lightfoot', 'Holdlamis');
insert into NEW_TABLE (id, first_name, app_name) values (237, 'Vulture, black', 'Duobam');
insert into NEW_TABLE (id, first_name, app_name) values (238, 'Brazilian tapir', 'Regrant');
insert into NEW_TABLE (id, first_name, app_name) values (239, 'Owl, madagascar hawk', 'Zoolab');
insert into NEW_TABLE (id, first_name, app_name) values (240, 'Bat-eared fox', 'Bamity');
insert into NEW_TABLE (id, first_name, app_name) values (241, 'Water monitor', 'Lotstring');
insert into NEW_TABLE (id, first_name, app_name) values (242, 'Otter, oriental short-clawed', 'Tresom');
insert into NEW_TABLE (id, first_name, app_name) values (243, 'Red and blue macaw', 'Fintone');
insert into NEW_TABLE (id, first_name, app_name) values (244, 'Mouflon', 'Viva');
insert into NEW_TABLE (id, first_name, app_name) values (245, 'Thirteen-lined squirrel', 'Tin');
insert into NEW_TABLE (id, first_name, app_name) values (246, 'Silver gull', 'Mat Lam Tam');
insert into NEW_TABLE (id, first_name, app_name) values (247, 'Deer, mule', 'Y-Solowarm');
insert into NEW_TABLE (id, first_name, app_name) values (248, 'Eland, common', 'Domainer');
insert into NEW_TABLE (id, first_name, app_name) values (249, 'Grey-footed squirrel', 'Stringtough');
insert into NEW_TABLE (id, first_name, app_name) values (250, 'Long-tailed jaeger', 'Alpha');
insert into NEW_TABLE (id, first_name, app_name) values (251, 'Lion, asian', 'Bytecard');
insert into NEW_TABLE (id, first_name, app_name) values (252, 'Black and white colobus', 'Duobam');
insert into NEW_TABLE (id, first_name, app_name) values (253, 'Dove, galapagos', 'Tresom');
insert into NEW_TABLE (id, first_name, app_name) values (254, 'Blue-breasted cordon bleu', 'Zathin');
insert into NEW_TABLE (id, first_name, app_name) values (255, 'Blackbuck', 'Greenlam');
insert into NEW_TABLE (id, first_name, app_name) values (256, 'American beaver', 'Zoolab');
insert into NEW_TABLE (id, first_name, app_name) values (257, 'Yellow-billed hornbill', 'Pannier');
insert into NEW_TABLE (id, first_name, app_name) values (258, 'Gecko, barking', 'Zathin');
insert into NEW_TABLE (id, first_name, app_name) values (259, 'Leadbeateri''s ground hornbill', 'Lotstring');
insert into NEW_TABLE (id, first_name, app_name) values (260, 'Japanese macaque', 'Greenlam');
insert into NEW_TABLE (id, first_name, app_name) values (261, 'American marten', 'Flexidy');
insert into NEW_TABLE (id, first_name, app_name) values (262, 'Common duiker', 'Span');
insert into NEW_TABLE (id, first_name, app_name) values (263, 'Green vine snake', 'Duobam');
insert into NEW_TABLE (id, first_name, app_name) values (264, 'African polecat', 'Gembucket');
insert into NEW_TABLE (id, first_name, app_name) values (265, 'Dragonfly, russian', 'Temp');
insert into NEW_TABLE (id, first_name, app_name) values (266, 'Baboon, yellow', 'Span');
insert into NEW_TABLE (id, first_name, app_name) values (267, 'Wallaroo, common', 'Overhold');
insert into NEW_TABLE (id, first_name, app_name) values (268, 'Striped hyena', 'Daltfresh');
insert into NEW_TABLE (id, first_name, app_name) values (269, 'Buffalo, asian water', 'Bigtax');
insert into NEW_TABLE (id, first_name, app_name) values (270, 'Quoll, spotted-tailed', 'Bitwolf');
insert into NEW_TABLE (id, first_name, app_name) values (271, 'Rhinoceros, white', 'Alphazap');
insert into NEW_TABLE (id, first_name, app_name) values (272, 'Salmon, sockeye', 'Voltsillam');
insert into NEW_TABLE (id, first_name, app_name) values (273, 'Common grenadier', 'Fintone');
insert into NEW_TABLE (id, first_name, app_name) values (274, 'Possum, pygmy', 'Namfix');
insert into NEW_TABLE (id, first_name, app_name) values (275, 'Wambenger, red-tailed', 'Mat Lam Tam');
insert into NEW_TABLE (id, first_name, app_name) values (276, 'Woodpecker, red-headed', 'Solarbreeze');
insert into NEW_TABLE (id, first_name, app_name) values (277, 'Crown of thorns starfish', 'Viva');
insert into NEW_TABLE (id, first_name, app_name) values (278, 'White-necked stork', 'Transcof');
insert into NEW_TABLE (id, first_name, app_name) values (279, 'Barking gecko', 'Hatity');
insert into NEW_TABLE (id, first_name, app_name) values (280, 'Spotted-tailed quoll', 'Redhold');
insert into NEW_TABLE (id, first_name, app_name) values (281, 'Emu', 'Ronstring');
insert into NEW_TABLE (id, first_name, app_name) values (282, 'Pelican, australian', 'Pannier');
insert into NEW_TABLE (id, first_name, app_name) values (283, 'Goose, canada', 'Y-find');
insert into NEW_TABLE (id, first_name, app_name) values (284, 'Polecat, african', 'Subin');
insert into NEW_TABLE (id, first_name, app_name) values (285, 'Lizard, collared', 'Flexidy');
insert into NEW_TABLE (id, first_name, app_name) values (286, 'Carmine bee-eater', 'Ronstring');
insert into NEW_TABLE (id, first_name, app_name) values (287, 'Asian false vampire bat', 'Pannier');
insert into NEW_TABLE (id, first_name, app_name) values (288, 'Crocodile, nile', 'Regrant');
insert into NEW_TABLE (id, first_name, app_name) values (289, 'Otter, brazilian', 'Alpha');
insert into NEW_TABLE (id, first_name, app_name) values (290, 'Creeper, black-tailed tree', 'Fintone');
insert into NEW_TABLE (id, first_name, app_name) values (291, 'Genet, small-spotted', 'Temp');
insert into NEW_TABLE (id, first_name, app_name) values (292, 'Macaque, bonnet', 'Fix San');
insert into NEW_TABLE (id, first_name, app_name) values (293, 'Squirrel, african bush', 'Gembucket');
insert into NEW_TABLE (id, first_name, app_name) values (294, 'Wombat, southern hairy-nosed', 'Flexidy');
insert into NEW_TABLE (id, first_name, app_name) values (295, 'Kingfisher, white-throated', 'Mat Lam Tam');
insert into NEW_TABLE (id, first_name, app_name) values (296, 'Lechwe, kafue flats', 'Flowdesk');
insert into NEW_TABLE (id, first_name, app_name) values (297, 'Malachite kingfisher', 'Fix San');
insert into NEW_TABLE (id, first_name, app_name) values (298, 'Rattlesnake, dusky', 'Tin');
insert into NEW_TABLE (id, first_name, app_name) values (299, 'Vicuna', 'Job');
insert into NEW_TABLE (id, first_name, app_name) values (300, 'Marmot, hoary', 'Home Ing');
insert into NEW_TABLE (id, first_name, app_name) values (301, 'Whale, baleen', 'Holdlamis');
insert into NEW_TABLE (id, first_name, app_name) values (302, 'Buffalo, wild water', 'Namfix');
insert into NEW_TABLE (id, first_name, app_name) values (303, 'Dragon, asian water', 'Sonsing');
insert into NEW_TABLE (id, first_name, app_name) values (304, 'Silver gull', 'Tin');
insert into NEW_TABLE (id, first_name, app_name) values (305, 'Squirrel, antelope ground', 'Sonair');
insert into NEW_TABLE (id, first_name, app_name) values (306, 'Giant heron', 'Stronghold');
insert into NEW_TABLE (id, first_name, app_name) values (307, 'Red meerkat', 'Ronstring');
insert into NEW_TABLE (id, first_name, app_name) values (308, 'Southern tamandua', 'Domainer');
insert into NEW_TABLE (id, first_name, app_name) values (309, 'Desert spiny lizard', 'Flexidy');
insert into NEW_TABLE (id, first_name, app_name) values (310, 'Stork, jabiru', 'Lotlux');
insert into NEW_TABLE (id, first_name, app_name) values (311, 'Lion, southern sea', 'Zathin');
insert into NEW_TABLE (id, first_name, app_name) values (312, 'Nubian bee-eater', 'Alpha');
insert into NEW_TABLE (id, first_name, app_name) values (313, 'Puma, south american', 'Gembucket');
insert into NEW_TABLE (id, first_name, app_name) values (314, 'Duck, comb', 'Redhold');
insert into NEW_TABLE (id, first_name, app_name) values (315, 'Jabiru stork', 'Zaam-Dox');
insert into NEW_TABLE (id, first_name, app_name) values (316, 'Dragon, komodo', 'Opela');
insert into NEW_TABLE (id, first_name, app_name) values (317, 'Buffalo, american', 'Treeflex');
insert into NEW_TABLE (id, first_name, app_name) values (318, 'Comb duck', 'Sonsing');
insert into NEW_TABLE (id, first_name, app_name) values (319, 'Chital', 'Lotstring');
insert into NEW_TABLE (id, first_name, app_name) values (320, 'Stick insect', 'Veribet');
insert into NEW_TABLE (id, first_name, app_name) values (321, 'Plover, blacksmith', 'Cardify');
insert into NEW_TABLE (id, first_name, app_name) values (322, 'Burmese brown mountain tortoise', 'Keylex');
insert into NEW_TABLE (id, first_name, app_name) values (323, 'Beaver, eurasian', 'Vagram');
insert into NEW_TABLE (id, first_name, app_name) values (324, 'Small-spotted genet', 'Zontrax');
insert into NEW_TABLE (id, first_name, app_name) values (325, 'Eastern box turtle', 'Job');
insert into NEW_TABLE (id, first_name, app_name) values (326, 'Duck, white-faced whistling', 'Rank');
insert into NEW_TABLE (id, first_name, app_name) values (327, 'Mynah, indian', 'Home Ing');
insert into NEW_TABLE (id, first_name, app_name) values (328, 'Cat, toddy', 'Flowdesk');
insert into NEW_TABLE (id, first_name, app_name) values (329, 'Tiger snake', 'Matsoft');
insert into NEW_TABLE (id, first_name, app_name) values (330, 'Netted rock dragon', 'Flexidy');
insert into NEW_TABLE (id, first_name, app_name) values (331, 'Cat, european wild', 'Viva');
insert into NEW_TABLE (id, first_name, app_name) values (332, 'European shelduck', 'Cardify');
insert into NEW_TABLE (id, first_name, app_name) values (333, 'Sparrow, house', 'Mat Lam Tam');
insert into NEW_TABLE (id, first_name, app_name) values (334, 'Blue-breasted cordon bleu', 'Redhold');
insert into NEW_TABLE (id, first_name, app_name) values (335, 'Vicuna', 'Toughjoyfax');
insert into NEW_TABLE (id, first_name, app_name) values (336, 'Bird, secretary', 'Redhold');
insert into NEW_TABLE (id, first_name, app_name) values (337, 'Mynah, indian', 'Flexidy');
insert into NEW_TABLE (id, first_name, app_name) values (338, 'Boar, wild', 'Namfix');
insert into NEW_TABLE (id, first_name, app_name) values (339, 'Lemur, sportive', 'Daltfresh');
insert into NEW_TABLE (id, first_name, app_name) values (340, 'Common green iguana', 'Bitwolf');
insert into NEW_TABLE (id, first_name, app_name) values (341, 'Squirrel, nelson ground', 'Voltsillam');
insert into NEW_TABLE (id, first_name, app_name) values (342, 'Polar bear', 'Viva');
insert into NEW_TABLE (id, first_name, app_name) values (343, 'Grant''s gazelle', 'Treeflex');
insert into NEW_TABLE (id, first_name, app_name) values (344, 'Salmon pink bird eater tarantula', 'Solarbreeze');
insert into NEW_TABLE (id, first_name, app_name) values (345, 'Gulls (unidentified)', 'Kanlam');
insert into NEW_TABLE (id, first_name, app_name) values (346, 'Coyote', 'Gembucket');
insert into NEW_TABLE (id, first_name, app_name) values (347, 'Wolf spider', 'Zontrax');
insert into NEW_TABLE (id, first_name, app_name) values (348, 'Indian porcupine', 'Toughjoyfax');
insert into NEW_TABLE (id, first_name, app_name) values (349, 'Yellow baboon', 'Bytecard');
insert into NEW_TABLE (id, first_name, app_name) values (350, 'Coyote', 'Overhold');
insert into NEW_TABLE (id, first_name, app_name) values (351, 'Blackbird, red-winged', 'Lotstring');
insert into NEW_TABLE (id, first_name, app_name) values (352, 'Blackish oystercatcher', 'Lotlux');
insert into NEW_TABLE (id, first_name, app_name) values (353, 'Gemsbok', 'Treeflex');
insert into NEW_TABLE (id, first_name, app_name) values (354, 'Snake, western patch-nosed', 'Home Ing');
insert into NEW_TABLE (id, first_name, app_name) values (355, 'Devil, tasmanian', 'Keylex');
insert into NEW_TABLE (id, first_name, app_name) values (356, 'Red-winged blackbird', 'Sonsing');
insert into NEW_TABLE (id, first_name, app_name) values (357, 'Silver gull', 'Aerified');
insert into NEW_TABLE (id, first_name, app_name) values (358, 'Oryx, fringe-eared', 'Zaam-Dox');
insert into NEW_TABLE (id, first_name, app_name) values (359, 'Sage hen', 'Voltsillam');
insert into NEW_TABLE (id, first_name, app_name) values (360, 'Porcupine, tree', 'Cardguard');
insert into NEW_TABLE (id, first_name, app_name) values (361, 'Russian dragonfly', 'Redhold');
insert into NEW_TABLE (id, first_name, app_name) values (362, 'Bandicoot, short-nosed', 'Tres-Zap');
insert into NEW_TABLE (id, first_name, app_name) values (363, 'Magnificent frigate bird', 'It');
insert into NEW_TABLE (id, first_name, app_name) values (364, 'Ring-tailed gecko', 'Lotlux');
insert into NEW_TABLE (id, first_name, app_name) values (365, 'Lemur, ring-tailed', 'Quo Lux');
insert into NEW_TABLE (id, first_name, app_name) values (366, 'Boa, cook''s tree', 'Cookley');
insert into NEW_TABLE (id, first_name, app_name) values (367, 'Stork, marabou', 'Hatity');
insert into NEW_TABLE (id, first_name, app_name) values (368, 'Galapagos mockingbird', 'Transcof');
insert into NEW_TABLE (id, first_name, app_name) values (369, 'Bandicoot, long-nosed', 'Tampflex');
insert into NEW_TABLE (id, first_name, app_name) values (370, 'Swan, black', 'Regrant');
insert into NEW_TABLE (id, first_name, app_name) values (371, 'Baboon, savanna', 'It');
insert into NEW_TABLE (id, first_name, app_name) values (372, 'Crab, sally lightfoot', 'Flowdesk');
insert into NEW_TABLE (id, first_name, app_name) values (373, 'Gaur', 'Ventosanzap');
insert into NEW_TABLE (id, first_name, app_name) values (374, 'Snake, western patch-nosed', 'Alpha');
insert into NEW_TABLE (id, first_name, app_name) values (375, 'Comb duck', 'Bamity');
insert into NEW_TABLE (id, first_name, app_name) values (376, 'Prehensile-tailed porcupine', 'Overhold');
insert into NEW_TABLE (id, first_name, app_name) values (377, 'Tinamou, elegant crested', 'Tin');
insert into NEW_TABLE (id, first_name, app_name) values (378, 'Dragon, ornate rock', 'Zoolab');
insert into NEW_TABLE (id, first_name, app_name) values (379, 'Alpaca', 'Zaam-Dox');
insert into NEW_TABLE (id, first_name, app_name) values (380, 'Antelope, roan', 'Cookley');
insert into NEW_TABLE (id, first_name, app_name) values (381, 'Bee-eater (unidentified)', 'Pannier');
insert into NEW_TABLE (id, first_name, app_name) values (382, 'Shrike, crimson-breasted', 'It');
insert into NEW_TABLE (id, first_name, app_name) values (383, 'Dog, african wild', 'Sonsing');
insert into NEW_TABLE (id, first_name, app_name) values (384, 'Gazelle, thomson''s', 'Andalax');
insert into NEW_TABLE (id, first_name, app_name) values (385, 'Crested screamer', 'Veribet');
insert into NEW_TABLE (id, first_name, app_name) values (386, 'Rainbow lory', 'Y-Solowarm');
insert into NEW_TABLE (id, first_name, app_name) values (387, 'Falcon, peregrine', 'Sonsing');
insert into NEW_TABLE (id, first_name, app_name) values (388, 'Mexican wolf', 'Vagram');
insert into NEW_TABLE (id, first_name, app_name) values (389, 'Elephant, african', 'Cardify');
insert into NEW_TABLE (id, first_name, app_name) values (390, 'Sheep, stone', 'Biodex');
insert into NEW_TABLE (id, first_name, app_name) values (391, 'American marten', 'Matsoft');
insert into NEW_TABLE (id, first_name, app_name) values (392, 'Loris, slender', 'Span');
insert into NEW_TABLE (id, first_name, app_name) values (393, 'Greater flamingo', 'Lotlux');
insert into NEW_TABLE (id, first_name, app_name) values (394, 'Silver-backed jackal', 'Tempsoft');
insert into NEW_TABLE (id, first_name, app_name) values (395, 'Swamp deer', 'Biodex');
insert into NEW_TABLE (id, first_name, app_name) values (396, 'Squirrel, european red', 'Trippledex');
insert into NEW_TABLE (id, first_name, app_name) values (397, 'Tortoise, burmese brown mountain', 'Flexidy');
insert into NEW_TABLE (id, first_name, app_name) values (398, 'Horned rattlesnake', 'Stronghold');
insert into NEW_TABLE (id, first_name, app_name) values (399, 'Sungazer, yellow-brown', 'Prodder');
insert into NEW_TABLE (id, first_name, app_name) values (400, 'Kalahari scrub robin', 'Regrant');
insert into NEW_TABLE (id, first_name, app_name) values (401, 'Boar, wild', 'Matsoft');
insert into NEW_TABLE (id, first_name, app_name) values (402, 'Sockeye salmon', 'Mat Lam Tam');
insert into NEW_TABLE (id, first_name, app_name) values (403, 'Crane, sarus', 'Konklab');
insert into NEW_TABLE (id, first_name, app_name) values (404, 'Bettong, brush-tailed', 'Regrant');
insert into NEW_TABLE (id, first_name, app_name) values (405, 'Bleu, blue-breasted cordon', 'Overhold');
insert into NEW_TABLE (id, first_name, app_name) values (406, 'Ass, asiatic wild', 'Holdlamis');
insert into NEW_TABLE (id, first_name, app_name) values (407, 'Canadian river otter', 'Temp');
insert into NEW_TABLE (id, first_name, app_name) values (408, 'Frilled lizard', 'Sonsing');
insert into NEW_TABLE (id, first_name, app_name) values (409, 'Jaeger, long-tailed', 'Sonsing');
insert into NEW_TABLE (id, first_name, app_name) values (410, 'Clark''s nutcracker', 'Cookley');
insert into NEW_TABLE (id, first_name, app_name) values (411, 'Tinamou, elegant crested', 'Tresom');
insert into NEW_TABLE (id, first_name, app_name) values (412, 'Squirrel, red', 'Y-find');
insert into NEW_TABLE (id, first_name, app_name) values (413, 'Collared lemming', 'Bigtax');
insert into NEW_TABLE (id, first_name, app_name) values (414, 'Blue catfish', 'Latlux');
insert into NEW_TABLE (id, first_name, app_name) values (415, 'Kookaburra, laughing', 'Prodder');
insert into NEW_TABLE (id, first_name, app_name) values (416, 'Flightless cormorant', 'Gembucket');
insert into NEW_TABLE (id, first_name, app_name) values (417, 'Genoveva', 'Hatity');
insert into NEW_TABLE (id, first_name, app_name) values (418, 'Porcupine, crested', 'Cookley');
insert into NEW_TABLE (id, first_name, app_name) values (419, 'Black rhinoceros', 'Wrapsafe');
insert into NEW_TABLE (id, first_name, app_name) values (420, 'Common boubou shrike', 'Andalax');
insert into NEW_TABLE (id, first_name, app_name) values (421, 'Cat, civet', 'Veribet');
insert into NEW_TABLE (id, first_name, app_name) values (422, 'Small-clawed otter', 'Fixflex');
insert into NEW_TABLE (id, first_name, app_name) values (423, 'Gray langur', 'Voyatouch');
insert into NEW_TABLE (id, first_name, app_name) values (424, 'Antelope, roan', 'Ventosanzap');
insert into NEW_TABLE (id, first_name, app_name) values (425, 'Dragon, netted rock', 'Fix San');
insert into NEW_TABLE (id, first_name, app_name) values (426, 'Urial', 'Ronstring');
insert into NEW_TABLE (id, first_name, app_name) values (427, 'Quoll, spotted-tailed', 'Trippledex');
insert into NEW_TABLE (id, first_name, app_name) values (428, 'Red-capped cardinal', 'Duobam');
insert into NEW_TABLE (id, first_name, app_name) values (429, 'White-tailed jackrabbit', 'Zamit');
insert into NEW_TABLE (id, first_name, app_name) values (430, 'Common brushtail possum', 'Tampflex');
insert into NEW_TABLE (id, first_name, app_name) values (431, 'Sacred ibis', 'Pannier');
insert into NEW_TABLE (id, first_name, app_name) values (432, 'Snake, eastern indigo', 'Aerified');
insert into NEW_TABLE (id, first_name, app_name) values (433, 'Square-lipped rhinoceros', 'Lotstring');
insert into NEW_TABLE (id, first_name, app_name) values (434, 'Long-tailed skua', 'It');
insert into NEW_TABLE (id, first_name, app_name) values (435, 'Blackish oystercatcher', 'Zathin');
insert into NEW_TABLE (id, first_name, app_name) values (436, 'Wallaby, dama', 'Alpha');
insert into NEW_TABLE (id, first_name, app_name) values (437, 'European beaver', 'Alphazap');
insert into NEW_TABLE (id, first_name, app_name) values (438, 'Dog, bush', 'Fixflex');
insert into NEW_TABLE (id, first_name, app_name) values (439, 'Otter, north american river', 'Matsoft');
insert into NEW_TABLE (id, first_name, app_name) values (440, 'Chickadee, black-capped', 'Fintone');
insert into NEW_TABLE (id, first_name, app_name) values (441, 'Bulbul, african red-eyed', 'Veribet');
insert into NEW_TABLE (id, first_name, app_name) values (442, 'Fox, asian red', 'Temp');
insert into NEW_TABLE (id, first_name, app_name) values (443, 'Polar bear', 'Duobam');
insert into NEW_TABLE (id, first_name, app_name) values (444, 'Tern, white-winged', 'Sub-Ex');
insert into NEW_TABLE (id, first_name, app_name) values (445, 'Western grey kangaroo', 'Cookley');
insert into NEW_TABLE (id, first_name, app_name) values (446, 'Hedgehog, south african', 'Wrapsafe');
insert into NEW_TABLE (id, first_name, app_name) values (447, 'Puffin, horned', 'Bitwolf');
insert into NEW_TABLE (id, first_name, app_name) values (448, 'Blue-breasted cordon bleu', 'Hatity');
insert into NEW_TABLE (id, first_name, app_name) values (449, 'Iguana, land', 'Stim');
insert into NEW_TABLE (id, first_name, app_name) values (450, 'Glossy starling (unidentified)', 'Tin');
insert into NEW_TABLE (id, first_name, app_name) values (451, 'Thrasher, curve-billed', 'Temp');
insert into NEW_TABLE (id, first_name, app_name) values (452, 'White-lipped peccary', 'Opela');
insert into NEW_TABLE (id, first_name, app_name) values (453, 'Possum, common brushtail', 'Redhold');
insert into NEW_TABLE (id, first_name, app_name) values (454, 'Trumpeter, green-winged', 'Tres-Zap');
insert into NEW_TABLE (id, first_name, app_name) values (455, 'Darter, african', 'Matsoft');
insert into NEW_TABLE (id, first_name, app_name) values (456, 'Chimpanzee', 'Stim');
insert into NEW_TABLE (id, first_name, app_name) values (457, 'White-cheeked pintail', 'Y-find');
insert into NEW_TABLE (id, first_name, app_name) values (458, 'Snake, buttermilk', 'Namfix');
insert into NEW_TABLE (id, first_name, app_name) values (459, 'Common wallaroo', 'Zontrax');
insert into NEW_TABLE (id, first_name, app_name) values (460, 'Southern elephant seal', 'Holdlamis');
insert into NEW_TABLE (id, first_name, app_name) values (461, 'Gecko, barking', 'Holdlamis');
insert into NEW_TABLE (id, first_name, app_name) values (462, 'Beaver, european', 'Solarbreeze');
insert into NEW_TABLE (id, first_name, app_name) values (463, 'Vulture, turkey', 'Flexidy');
insert into NEW_TABLE (id, first_name, app_name) values (464, 'Timber wolf', 'Job');
insert into NEW_TABLE (id, first_name, app_name) values (465, 'Steller''s sea lion', 'Treeflex');
insert into NEW_TABLE (id, first_name, app_name) values (466, 'Cattle egret', 'Tempsoft');
insert into NEW_TABLE (id, first_name, app_name) values (467, 'Wallaby, whip-tailed', 'Tin');
insert into NEW_TABLE (id, first_name, app_name) values (468, 'Antelope ground squirrel', 'Cardify');
insert into NEW_TABLE (id, first_name, app_name) values (469, 'Praying mantis (unidentified)', 'Daltfresh');
insert into NEW_TABLE (id, first_name, app_name) values (470, 'Madagascar hawk owl', 'Ronstring');
insert into NEW_TABLE (id, first_name, app_name) values (471, 'Snake, buttermilk', 'Andalax');
insert into NEW_TABLE (id, first_name, app_name) values (472, 'Tamandua, southern', 'Asoka');
insert into NEW_TABLE (id, first_name, app_name) values (473, 'Possum, golden brush-tailed', 'Tin');
insert into NEW_TABLE (id, first_name, app_name) values (474, 'Dik, kirk''s dik', 'Transcof');
insert into NEW_TABLE (id, first_name, app_name) values (475, 'Oryx, fringe-eared', 'Ronstring');
insert into NEW_TABLE (id, first_name, app_name) values (476, 'Greylag goose', 'Stringtough');
insert into NEW_TABLE (id, first_name, app_name) values (477, 'Lion, california sea', 'Sub-Ex');
insert into NEW_TABLE (id, first_name, app_name) values (478, 'Asian lion', 'Mat Lam Tam');
insert into NEW_TABLE (id, first_name, app_name) values (479, 'Crowned hawk-eagle', 'Transcof');
insert into NEW_TABLE (id, first_name, app_name) values (480, 'Robin, kalahari scrub', 'Prodder');
insert into NEW_TABLE (id, first_name, app_name) values (481, 'Western patch-nosed snake', 'Konklab');
insert into NEW_TABLE (id, first_name, app_name) values (482, 'Native cat', 'Alphazap');
insert into NEW_TABLE (id, first_name, app_name) values (483, 'Nelson ground squirrel', 'Rank');
insert into NEW_TABLE (id, first_name, app_name) values (484, 'Kalahari scrub robin', 'Greenlam');
insert into NEW_TABLE (id, first_name, app_name) values (485, 'Penguin, magellanic', 'Fix San');
insert into NEW_TABLE (id, first_name, app_name) values (486, 'Shrike, crimson-breasted', 'Tempsoft');
insert into NEW_TABLE (id, first_name, app_name) values (487, 'Shrike, southern white-crowned', 'Lotstring');
insert into NEW_TABLE (id, first_name, app_name) values (488, 'Pelican, brown', 'Bamity');
insert into NEW_TABLE (id, first_name, app_name) values (489, 'Kalahari scrub robin', 'Bamity');
insert into NEW_TABLE (id, first_name, app_name) values (490, 'Rabbit, eastern cottontail', 'Biodex');
insert into NEW_TABLE (id, first_name, app_name) values (491, 'Hudsonian godwit', 'Fintone');
insert into NEW_TABLE (id, first_name, app_name) values (492, 'Crane, wattled', 'Konklux');
insert into NEW_TABLE (id, first_name, app_name) values (493, 'Stanley crane', 'Stronghold');
insert into NEW_TABLE (id, first_name, app_name) values (494, 'Bee-eater, carmine', 'Prodder');
insert into NEW_TABLE (id, first_name, app_name) values (495, 'Indian porcupine', 'Bigtax');
insert into NEW_TABLE (id, first_name, app_name) values (496, 'Gull, southern black-backed', 'Tin');
insert into NEW_TABLE (id, first_name, app_name) values (497, 'Monster, gila', 'Tin');
insert into NEW_TABLE (id, first_name, app_name) values (498, 'Heron, boat-billed', 'Redhold');
insert into NEW_TABLE (id, first_name, app_name) values (499, 'Common eland', 'Subin');
insert into NEW_TABLE (id, first_name, app_name) values (500, 'Grey lourie', 'Gembucket');
insert into NEW_TABLE (id, first_name, app_name) values (501, 'Green-winged macaw', 'Job');
insert into NEW_TABLE (id, first_name, app_name) values (502, 'White-eye, pale', 'Treeflex');
insert into NEW_TABLE (id, first_name, app_name) values (503, 'Sage hen', 'Cardguard');
insert into NEW_TABLE (id, first_name, app_name) values (504, 'Grenadier, common', 'Latlux');
insert into NEW_TABLE (id, first_name, app_name) values (505, 'Gambel''s quail', 'Temp');
insert into NEW_TABLE (id, first_name, app_name) values (506, 'Brush-tailed phascogale', 'Bitchip');
insert into NEW_TABLE (id, first_name, app_name) values (507, 'Ibis, puna', 'Prodder');
insert into NEW_TABLE (id, first_name, app_name) values (508, 'Fox, savanna', 'Overhold');
insert into NEW_TABLE (id, first_name, app_name) values (509, 'Antechinus, brown', 'Alphazap');
insert into NEW_TABLE (id, first_name, app_name) values (510, 'Ring-necked pheasant', 'Bamity');
insert into NEW_TABLE (id, first_name, app_name) values (511, 'Squirrel, palm', 'Sonair');
insert into NEW_TABLE (id, first_name, app_name) values (512, 'Buffalo, asian water', 'Transcof');
insert into NEW_TABLE (id, first_name, app_name) values (513, 'Hummingbird (unidentified)', 'Toughjoyfax');
insert into NEW_TABLE (id, first_name, app_name) values (514, 'Lemur, sportive', 'Stringtough');
insert into NEW_TABLE (id, first_name, app_name) values (515, 'Dove, rock', 'Bamity');
insert into NEW_TABLE (id, first_name, app_name) values (516, 'Waxbill, blue', 'Viva');
insert into NEW_TABLE (id, first_name, app_name) values (517, 'Capuchin, weeper', 'Aerified');
insert into NEW_TABLE (id, first_name, app_name) values (518, 'Indian porcupine', 'Holdlamis');
insert into NEW_TABLE (id, first_name, app_name) values (519, 'White-fronted bee-eater', 'Daltfresh');
insert into NEW_TABLE (id, first_name, app_name) values (520, 'Brazilian otter', 'Zaam-Dox');
insert into NEW_TABLE (id, first_name, app_name) values (521, 'Bettong, brush-tailed', 'Ronstring');
insert into NEW_TABLE (id, first_name, app_name) values (522, 'Kangaroo, black-faced', 'Zontrax');
insert into NEW_TABLE (id, first_name, app_name) values (523, 'Cockatoo, red-tailed', 'Ventosanzap');
insert into NEW_TABLE (id, first_name, app_name) values (524, 'Raccoon, common', 'Tresom');
insert into NEW_TABLE (id, first_name, app_name) values (525, 'Red-tailed cockatoo', 'Sonsing');
insert into NEW_TABLE (id, first_name, app_name) values (526, 'Common langur', 'Sonsing');
insert into NEW_TABLE (id, first_name, app_name) values (527, 'Lion, australian sea', 'Konklux');
insert into NEW_TABLE (id, first_name, app_name) values (528, 'Colobus, black and white', 'Bitchip');
insert into NEW_TABLE (id, first_name, app_name) values (529, 'Gray langur', 'Veribet');
insert into NEW_TABLE (id, first_name, app_name) values (530, 'Monitor, water', 'Opela');
insert into NEW_TABLE (id, first_name, app_name) values (531, 'Eurasian beaver', 'Temp');
insert into NEW_TABLE (id, first_name, app_name) values (532, 'Gecko, barking', 'Konklab');
insert into NEW_TABLE (id, first_name, app_name) values (533, 'Golden-mantled ground squirrel', 'Flexidy');
insert into NEW_TABLE (id, first_name, app_name) values (534, 'Dove, laughing', 'Cardify');
insert into NEW_TABLE (id, first_name, app_name) values (535, 'Flamingo, greater', 'Job');
insert into NEW_TABLE (id, first_name, app_name) values (536, 'Cormorant, pied', 'Voltsillam');
insert into NEW_TABLE (id, first_name, app_name) values (537, 'Hummingbird (unidentified)', 'Bytecard');
insert into NEW_TABLE (id, first_name, app_name) values (538, 'Yellow-billed hornbill', 'Y-Solowarm');
insert into NEW_TABLE (id, first_name, app_name) values (539, 'Southern lapwing', 'Rank');
insert into NEW_TABLE (id, first_name, app_name) values (540, 'Verreaux''s sifaka', 'Bigtax');
insert into NEW_TABLE (id, first_name, app_name) values (541, 'Helmeted guinea fowl', 'Tres-Zap');
insert into NEW_TABLE (id, first_name, app_name) values (542, 'Mexican beaded lizard', 'Transcof');
insert into NEW_TABLE (id, first_name, app_name) values (543, 'Southern ground hornbill', 'Regrant');
insert into NEW_TABLE (id, first_name, app_name) values (544, 'Ant (unidentified)', 'Transcof');
insert into NEW_TABLE (id, first_name, app_name) values (545, 'Common ringtail', 'Tin');
insert into NEW_TABLE (id, first_name, app_name) values (546, 'Mouse, four-striped grass', 'Vagram');
insert into NEW_TABLE (id, first_name, app_name) values (547, 'Four-horned antelope', 'Greenlam');
insert into NEW_TABLE (id, first_name, app_name) values (548, 'Bushbuck', 'Tres-Zap');
insert into NEW_TABLE (id, first_name, app_name) values (549, 'Deer, red', 'Stringtough');
insert into NEW_TABLE (id, first_name, app_name) values (550, 'Flicker, campo', 'Fix San');
insert into NEW_TABLE (id, first_name, app_name) values (551, 'Langur, common', 'Fix San');
insert into NEW_TABLE (id, first_name, app_name) values (552, 'Southern tamandua', 'Prodder');
insert into NEW_TABLE (id, first_name, app_name) values (553, 'Badger, american', 'Gembucket');
insert into NEW_TABLE (id, first_name, app_name) values (554, 'Malagasy ground boa', 'Wrapsafe');
insert into NEW_TABLE (id, first_name, app_name) values (555, 'Gray rhea', 'Tampflex');
insert into NEW_TABLE (id, first_name, app_name) values (556, 'Stork, european', 'Voltsillam');
insert into NEW_TABLE (id, first_name, app_name) values (557, 'Peccary, white-lipped', 'Biodex');
insert into NEW_TABLE (id, first_name, app_name) values (558, 'Large cormorant', 'Flexidy');
insert into NEW_TABLE (id, first_name, app_name) values (559, 'Pintail, white-cheeked', 'Latlux');
insert into NEW_TABLE (id, first_name, app_name) values (560, 'Skua, great', 'Voltsillam');
insert into NEW_TABLE (id, first_name, app_name) values (561, 'Bee-eater, carmine', 'Trippledex');
insert into NEW_TABLE (id, first_name, app_name) values (562, 'Snake, buttermilk', 'Zontrax');
insert into NEW_TABLE (id, first_name, app_name) values (563, 'Spotted deer', 'Rank');
insert into NEW_TABLE (id, first_name, app_name) values (564, 'Nelson ground squirrel', 'Hatity');
insert into NEW_TABLE (id, first_name, app_name) values (565, 'White-winged tern', 'Bytecard');
insert into NEW_TABLE (id, first_name, app_name) values (566, 'Loris, slender', 'Latlux');
insert into NEW_TABLE (id, first_name, app_name) values (567, 'Horned lark', 'Cardguard');
insert into NEW_TABLE (id, first_name, app_name) values (568, 'Woodrat (unidentified)', 'Voltsillam');
insert into NEW_TABLE (id, first_name, app_name) values (569, 'Mexican wolf', 'Keylex');
insert into NEW_TABLE (id, first_name, app_name) values (570, 'Pocket gopher (unidentified)', 'Ronstring');
insert into NEW_TABLE (id, first_name, app_name) values (571, 'Falcon, peregrine', 'Andalax');
insert into NEW_TABLE (id, first_name, app_name) values (572, 'Gray rhea', 'Biodex');
insert into NEW_TABLE (id, first_name, app_name) values (573, 'Partridge, coqui', 'Y-Solowarm');
insert into NEW_TABLE (id, first_name, app_name) values (574, 'Shrike, southern white-crowned', 'Asoka');
insert into NEW_TABLE (id, first_name, app_name) values (575, 'Swan, black', 'Zathin');
insert into NEW_TABLE (id, first_name, app_name) values (576, 'Catfish, blue', 'Voltsillam');
insert into NEW_TABLE (id, first_name, app_name) values (577, 'Creeper, black-tailed tree', 'Quo Lux');
insert into NEW_TABLE (id, first_name, app_name) values (578, 'Red-tailed wambenger', 'Zaam-Dox');
insert into NEW_TABLE (id, first_name, app_name) values (579, 'Zebra, plains', 'Bitchip');
insert into NEW_TABLE (id, first_name, app_name) values (580, 'Crab, red lava', 'Sonsing');
insert into NEW_TABLE (id, first_name, app_name) values (581, 'Australian brush turkey', 'Cookley');
insert into NEW_TABLE (id, first_name, app_name) values (582, 'Crab-eating fox', 'Aerified');
insert into NEW_TABLE (id, first_name, app_name) values (583, 'Bandicoot, southern brown', 'Fix San');
insert into NEW_TABLE (id, first_name, app_name) values (584, 'Great cormorant', 'Fixflex');
insert into NEW_TABLE (id, first_name, app_name) values (585, 'Colobus, magistrate black', 'Duobam');
insert into NEW_TABLE (id, first_name, app_name) values (586, 'Shelduck, european', 'Wrapsafe');
insert into NEW_TABLE (id, first_name, app_name) values (587, 'Common dolphin', 'Prodder');
insert into NEW_TABLE (id, first_name, app_name) values (588, 'Pronghorn', 'Y-find');
insert into NEW_TABLE (id, first_name, app_name) values (589, 'Gila monster', 'Ventosanzap');
insert into NEW_TABLE (id, first_name, app_name) values (590, 'Toddy cat', 'Y-Solowarm');
insert into NEW_TABLE (id, first_name, app_name) values (591, 'Crab, sally lightfoot', 'Tampflex');
insert into NEW_TABLE (id, first_name, app_name) values (592, 'Eastern grey kangaroo', 'Bamity');
insert into NEW_TABLE (id, first_name, app_name) values (593, 'Red-billed buffalo weaver', 'Lotstring');
insert into NEW_TABLE (id, first_name, app_name) values (594, 'North American river otter', 'Zamit');
insert into NEW_TABLE (id, first_name, app_name) values (595, 'Lizard (unidentified)', 'Bamity');
insert into NEW_TABLE (id, first_name, app_name) values (596, 'Penguin, fairy', 'Home Ing');
insert into NEW_TABLE (id, first_name, app_name) values (597, 'Cat, civet', 'Zaam-Dox');
insert into NEW_TABLE (id, first_name, app_name) values (598, 'Albatross, galapagos', 'Job');
insert into NEW_TABLE (id, first_name, app_name) values (599, 'Red-billed tropic bird', 'It');
insert into NEW_TABLE (id, first_name, app_name) values (600, 'Cobra, cape', 'Otcom');
insert into NEW_TABLE (id, first_name, app_name) values (601, 'Rock dove', 'Fixflex');
insert into NEW_TABLE (id, first_name, app_name) values (602, 'Sambar', 'Zaam-Dox');
insert into NEW_TABLE (id, first_name, app_name) values (603, 'White-eye, pale', 'Stim');
insert into NEW_TABLE (id, first_name, app_name) values (604, 'American black bear', 'Bytecard');
insert into NEW_TABLE (id, first_name, app_name) values (605, 'Indian tree pie', 'Zaam-Dox');
insert into NEW_TABLE (id, first_name, app_name) values (606, 'Sheathbill, snowy', 'Otcom');
insert into NEW_TABLE (id, first_name, app_name) values (607, 'Spurfowl, yellow-necked', 'Fix San');
insert into NEW_TABLE (id, first_name, app_name) values (608, 'Wallaby, dama', 'Tampflex');
insert into NEW_TABLE (id, first_name, app_name) values (609, 'Emerald-spotted wood dove', 'Y-Solowarm');
insert into NEW_TABLE (id, first_name, app_name) values (610, 'Jaeger, long-tailed', 'Greenlam');
insert into NEW_TABLE (id, first_name, app_name) values (611, 'Swan, black', 'Redhold');
insert into NEW_TABLE (id, first_name, app_name) values (612, 'Eagle, bateleur', 'Aerified');
insert into NEW_TABLE (id, first_name, app_name) values (613, 'Pigeon, wood', 'Fix San');
insert into NEW_TABLE (id, first_name, app_name) values (614, 'Sheep, stone', 'Regrant');
insert into NEW_TABLE (id, first_name, app_name) values (615, 'Booby, blue-faced', 'Otcom');
insert into NEW_TABLE (id, first_name, app_name) values (616, 'Tasmanian devil', 'Keylex');
insert into NEW_TABLE (id, first_name, app_name) values (617, 'Reindeer', 'Voyatouch');
insert into NEW_TABLE (id, first_name, app_name) values (618, 'Hanuman langur', 'Andalax');
insert into NEW_TABLE (id, first_name, app_name) values (619, 'Partridge, coqui', 'Lotlux');
insert into NEW_TABLE (id, first_name, app_name) values (620, 'Boa, emerald green tree', 'Prodder');
insert into NEW_TABLE (id, first_name, app_name) values (621, 'Starling, cape', 'Namfix');
insert into NEW_TABLE (id, first_name, app_name) values (622, 'Waxbill, blue', 'Subin');
insert into NEW_TABLE (id, first_name, app_name) values (623, 'Barking gecko', 'Zontrax');
insert into NEW_TABLE (id, first_name, app_name) values (624, 'Tern, royal', 'Y-find');
insert into NEW_TABLE (id, first_name, app_name) values (625, 'Vulture, white-rumped', 'Asoka');
insert into NEW_TABLE (id, first_name, app_name) values (626, 'African fish eagle', 'Y-Solowarm');
insert into NEW_TABLE (id, first_name, app_name) values (627, 'Rainbow lory', 'Lotlux');
insert into NEW_TABLE (id, first_name, app_name) values (628, 'Toucan, white-throated', 'Rank');
insert into NEW_TABLE (id, first_name, app_name) values (629, 'Screamer, crested', 'It');
insert into NEW_TABLE (id, first_name, app_name) values (630, 'Lion, southern sea', 'Alphazap');
insert into NEW_TABLE (id, first_name, app_name) values (631, 'Serval', 'Cardify');
insert into NEW_TABLE (id, first_name, app_name) values (632, 'African darter', 'Subin');
insert into NEW_TABLE (id, first_name, app_name) values (633, 'Pelican, eastern white', 'Gembucket');
insert into NEW_TABLE (id, first_name, app_name) values (634, 'Crested bunting', 'Treeflex');
insert into NEW_TABLE (id, first_name, app_name) values (635, 'Brush-tailed bettong', 'Subin');
insert into NEW_TABLE (id, first_name, app_name) values (636, 'Tinamou, elegant crested', 'Alpha');
insert into NEW_TABLE (id, first_name, app_name) values (637, 'Stanley bustard', 'Kanlam');
insert into NEW_TABLE (id, first_name, app_name) values (638, 'Lion, african', 'Prodder');
insert into NEW_TABLE (id, first_name, app_name) values (639, 'Potoroo', 'Hatity');
insert into NEW_TABLE (id, first_name, app_name) values (640, 'Savannah deer (unidentified)', 'Greenlam');
insert into NEW_TABLE (id, first_name, app_name) values (641, 'Lemur, lesser mouse', 'Bamity');
insert into NEW_TABLE (id, first_name, app_name) values (642, 'Eastern cottontail rabbit', 'Fix San');
insert into NEW_TABLE (id, first_name, app_name) values (643, 'Cape clawless otter', 'Trippledex');
insert into NEW_TABLE (id, first_name, app_name) values (644, 'Spotted wood sandpiper', 'Greenlam');
insert into NEW_TABLE (id, first_name, app_name) values (645, 'Dolphin, striped', 'Domainer');
insert into NEW_TABLE (id, first_name, app_name) values (646, 'Impala', 'Ventosanzap');
insert into NEW_TABLE (id, first_name, app_name) values (647, 'Burmese black mountain tortoise', 'Alphazap');
insert into NEW_TABLE (id, first_name, app_name) values (648, 'Mongoose, small indian', 'Redhold');
insert into NEW_TABLE (id, first_name, app_name) values (649, 'Asiatic jackal', 'Tampflex');
insert into NEW_TABLE (id, first_name, app_name) values (650, 'Mississippi alligator', 'Home Ing');
insert into NEW_TABLE (id, first_name, app_name) values (651, 'Stork, european', 'Regrant');
insert into NEW_TABLE (id, first_name, app_name) values (652, 'Wild boar', 'Tresom');
insert into NEW_TABLE (id, first_name, app_name) values (653, 'Chameleon (unidentified)', 'Biodex');
insert into NEW_TABLE (id, first_name, app_name) values (654, 'Peacock, blue', 'Fixflex');
insert into NEW_TABLE (id, first_name, app_name) values (655, 'Eastern cottontail rabbit', 'Flexidy');
insert into NEW_TABLE (id, first_name, app_name) values (656, 'Snowy sheathbill', 'Temp');
insert into NEW_TABLE (id, first_name, app_name) values (657, 'White-browed owl', 'Home Ing');
insert into NEW_TABLE (id, first_name, app_name) values (658, 'Black-tailed tree creeper', 'Ronstring');
insert into NEW_TABLE (id, first_name, app_name) values (659, 'White-winged dove', 'Matsoft');
insert into NEW_TABLE (id, first_name, app_name) values (660, 'Southern tamandua', 'Overhold');
insert into NEW_TABLE (id, first_name, app_name) values (661, 'Kangaroo, black-faced', 'Quo Lux');
insert into NEW_TABLE (id, first_name, app_name) values (662, 'Wallaby, euro', 'Sonair');
insert into NEW_TABLE (id, first_name, app_name) values (663, 'Hyena, striped', 'Tresom');
insert into NEW_TABLE (id, first_name, app_name) values (664, 'Marten, american', 'Cardify');
insert into NEW_TABLE (id, first_name, app_name) values (665, 'Blue crane', 'Voyatouch');
insert into NEW_TABLE (id, first_name, app_name) values (666, 'Hottentot teal', 'Overhold');
insert into NEW_TABLE (id, first_name, app_name) values (667, 'Long-necked turtle', 'Tres-Zap');
insert into NEW_TABLE (id, first_name, app_name) values (668, 'Asian red fox', 'Flowdesk');
insert into NEW_TABLE (id, first_name, app_name) values (669, 'Elk, Wapiti', 'Cardguard');
insert into NEW_TABLE (id, first_name, app_name) values (670, 'Vicuna', 'Domainer');
insert into NEW_TABLE (id, first_name, app_name) values (671, 'Kangaroo, eastern grey', 'Stronghold');
insert into NEW_TABLE (id, first_name, app_name) values (672, 'Grey-footed squirrel', 'Cardguard');
insert into NEW_TABLE (id, first_name, app_name) values (673, 'Hornbill, red-billed', 'Bigtax');
insert into NEW_TABLE (id, first_name, app_name) values (674, 'Common waterbuck', 'Stringtough');
insert into NEW_TABLE (id, first_name, app_name) values (675, 'Porcupine, tree', 'Namfix');
insert into NEW_TABLE (id, first_name, app_name) values (676, 'Dove, little brown', 'Asoka');
insert into NEW_TABLE (id, first_name, app_name) values (677, 'Striped skunk', 'Gembucket');
insert into NEW_TABLE (id, first_name, app_name) values (678, 'Porcupine, tree', 'Alphazap');
insert into NEW_TABLE (id, first_name, app_name) values (679, 'Ibis, glossy', 'Bitwolf');
insert into NEW_TABLE (id, first_name, app_name) values (680, 'Eastern fox squirrel', 'Fintone');
insert into NEW_TABLE (id, first_name, app_name) values (681, 'Cat, kaffir', 'Bamity');
insert into NEW_TABLE (id, first_name, app_name) values (682, 'Water monitor', 'Overhold');
insert into NEW_TABLE (id, first_name, app_name) values (683, 'Kongoni', 'Zaam-Dox');
insert into NEW_TABLE (id, first_name, app_name) values (684, 'Galapagos penguin', 'Matsoft');
insert into NEW_TABLE (id, first_name, app_name) values (685, 'Feral rock pigeon', 'Trippledex');
insert into NEW_TABLE (id, first_name, app_name) values (686, 'Gecko, bent-toed', 'Prodder');
insert into NEW_TABLE (id, first_name, app_name) values (687, 'Zorilla', 'Domainer');
insert into NEW_TABLE (id, first_name, app_name) values (688, 'Tortoise, burmese brown mountain', 'Gembucket');
insert into NEW_TABLE (id, first_name, app_name) values (689, 'Olive baboon', 'Gembucket');
insert into NEW_TABLE (id, first_name, app_name) values (690, 'Kori bustard', 'Zathin');
insert into NEW_TABLE (id, first_name, app_name) values (691, 'River wallaby', 'Tresom');
insert into NEW_TABLE (id, first_name, app_name) values (692, 'Roseat flamingo', 'Cookley');
insert into NEW_TABLE (id, first_name, app_name) values (693, 'Asiatic wild ass', 'Tempsoft');
insert into NEW_TABLE (id, first_name, app_name) values (694, 'Ground legaan', 'Subin');
insert into NEW_TABLE (id, first_name, app_name) values (695, 'Yellow baboon', 'Matsoft');
insert into NEW_TABLE (id, first_name, app_name) values (696, 'Fisher', 'Tresom');
insert into NEW_TABLE (id, first_name, app_name) values (697, 'Brown capuchin', 'Trippledex');
insert into NEW_TABLE (id, first_name, app_name) values (698, 'Jackal, golden', 'Y-Solowarm');
insert into NEW_TABLE (id, first_name, app_name) values (699, 'Galapagos dove', 'Stim');
insert into NEW_TABLE (id, first_name, app_name) values (700, 'Gray rhea', 'Y-Solowarm');
insert into NEW_TABLE (id, first_name, app_name) values (701, 'White-fronted capuchin', 'Keylex');
insert into NEW_TABLE (id, first_name, app_name) values (702, 'Long-billed corella', 'Zoolab');
insert into NEW_TABLE (id, first_name, app_name) values (703, 'Emu', 'Toughjoyfax');
insert into NEW_TABLE (id, first_name, app_name) values (704, 'North American red fox', 'Temp');
insert into NEW_TABLE (id, first_name, app_name) values (705, 'Lizard, blue-tongued', 'Y-find');
insert into NEW_TABLE (id, first_name, app_name) values (706, 'Dove, mourning collared', 'Domainer');
insert into NEW_TABLE (id, first_name, app_name) values (707, 'Galapagos albatross', 'Tin');
insert into NEW_TABLE (id, first_name, app_name) values (708, 'Eagle, crowned', 'Trippledex');
insert into NEW_TABLE (id, first_name, app_name) values (709, 'South American meadowlark (unidentified)', 'Stim');
insert into NEW_TABLE (id, first_name, app_name) values (710, 'Mongoose, banded', 'Y-find');
insert into NEW_TABLE (id, first_name, app_name) values (711, 'Eurasian hoopoe', 'Job');
insert into NEW_TABLE (id, first_name, app_name) values (712, 'Red-necked phalarope', 'Fix San');
insert into NEW_TABLE (id, first_name, app_name) values (713, 'American bison', 'Subin');
insert into NEW_TABLE (id, first_name, app_name) values (714, 'Goose, canada', 'Subin');
insert into NEW_TABLE (id, first_name, app_name) values (715, 'Lizard (unidentified)', 'Home Ing');
insert into NEW_TABLE (id, first_name, app_name) values (716, 'Cat, civet', 'Sonair');
insert into NEW_TABLE (id, first_name, app_name) values (717, 'Red sheep', 'Mat Lam Tam');
insert into NEW_TABLE (id, first_name, app_name) values (718, 'White-fronted capuchin', 'Namfix');
insert into NEW_TABLE (id, first_name, app_name) values (719, 'Denham''s bustard', 'Bamity');
insert into NEW_TABLE (id, first_name, app_name) values (720, 'Suricate', 'Tampflex');
insert into NEW_TABLE (id, first_name, app_name) values (721, 'Alpaca', 'Stringtough');
insert into NEW_TABLE (id, first_name, app_name) values (722, 'Catfish, blue', 'Lotstring');
insert into NEW_TABLE (id, first_name, app_name) values (723, 'Comb duck', 'Tempsoft');
insert into NEW_TABLE (id, first_name, app_name) values (724, 'Burmese brown mountain tortoise', 'Fixflex');
insert into NEW_TABLE (id, first_name, app_name) values (725, 'Blue-tongued lizard', 'Tempsoft');
insert into NEW_TABLE (id, first_name, app_name) values (726, 'Drongo, fork-tailed', 'Namfix');
insert into NEW_TABLE (id, first_name, app_name) values (727, 'Falcon, prairie', 'Bamity');
insert into NEW_TABLE (id, first_name, app_name) values (728, 'Masked booby', 'Tempsoft');
insert into NEW_TABLE (id, first_name, app_name) values (729, 'Black-necked stork', 'Flowdesk');
insert into NEW_TABLE (id, first_name, app_name) values (730, 'Great cormorant', 'Bitwolf');
insert into NEW_TABLE (id, first_name, app_name) values (731, 'Crow, house', 'Rank');
insert into NEW_TABLE (id, first_name, app_name) values (732, 'Yellow-rumped siskin', 'Greenlam');
insert into NEW_TABLE (id, first_name, app_name) values (733, 'Kafue flats lechwe', 'Namfix');
insert into NEW_TABLE (id, first_name, app_name) values (734, 'Sun gazer', 'Cardify');
insert into NEW_TABLE (id, first_name, app_name) values (735, 'Crow, house', 'Fintone');
insert into NEW_TABLE (id, first_name, app_name) values (736, 'Four-spotted skimmer', 'It');
insert into NEW_TABLE (id, first_name, app_name) values (737, 'Egyptian goose', 'Redhold');
insert into NEW_TABLE (id, first_name, app_name) values (738, 'Red and blue macaw', 'Lotlux');
insert into NEW_TABLE (id, first_name, app_name) values (739, 'Pintail, white-cheeked', 'Matsoft');
insert into NEW_TABLE (id, first_name, app_name) values (740, 'Brown pelican', 'Alphazap');
insert into NEW_TABLE (id, first_name, app_name) values (741, 'Phascogale, brush-tailed', 'Home Ing');
insert into NEW_TABLE (id, first_name, app_name) values (742, 'Porcupine, indian', 'Stim');
insert into NEW_TABLE (id, first_name, app_name) values (743, 'Bandicoot, long-nosed', 'Asoka');
insert into NEW_TABLE (id, first_name, app_name) values (744, 'Deer, red', 'Stronghold');
insert into NEW_TABLE (id, first_name, app_name) values (745, 'Kookaburra, laughing', 'Vagram');
insert into NEW_TABLE (id, first_name, app_name) values (746, 'Prehensile-tailed porcupine', 'Y-find');
insert into NEW_TABLE (id, first_name, app_name) values (747, 'Lion, australian sea', 'Opela');
insert into NEW_TABLE (id, first_name, app_name) values (748, 'Weeper capuchin', 'Bamity');
insert into NEW_TABLE (id, first_name, app_name) values (749, 'Goose, snow', 'Bigtax');
insert into NEW_TABLE (id, first_name, app_name) values (750, 'Mudskipper (unidentified)', 'Kanlam');
insert into NEW_TABLE (id, first_name, app_name) values (751, 'Cockatoo, red-tailed', 'Fix San');
insert into NEW_TABLE (id, first_name, app_name) values (752, 'Jacana, african', 'Stringtough');
insert into NEW_TABLE (id, first_name, app_name) values (753, 'Porcupine, indian', 'Sub-Ex');
insert into NEW_TABLE (id, first_name, app_name) values (754, 'Carmine bee-eater', 'Zathin');
insert into NEW_TABLE (id, first_name, app_name) values (755, 'Frilled dragon', 'Opela');
insert into NEW_TABLE (id, first_name, app_name) values (756, 'Dove, ring', 'Prodder');
insert into NEW_TABLE (id, first_name, app_name) values (757, 'Crested screamer', 'Zathin');
insert into NEW_TABLE (id, first_name, app_name) values (758, 'Superb starling', 'Tin');
insert into NEW_TABLE (id, first_name, app_name) values (759, 'Striped hyena', 'Overhold');
insert into NEW_TABLE (id, first_name, app_name) values (760, 'Wallaroo, common', 'Flowdesk');
insert into NEW_TABLE (id, first_name, app_name) values (761, 'Dik, kirk''s dik', 'Solarbreeze');
insert into NEW_TABLE (id, first_name, app_name) values (762, 'Hare, arctic', 'Pannier');
insert into NEW_TABLE (id, first_name, app_name) values (763, 'Red-billed hornbill', 'Otcom');
insert into NEW_TABLE (id, first_name, app_name) values (764, 'Western lowland gorilla', 'Domainer');
insert into NEW_TABLE (id, first_name, app_name) values (765, 'Coqui partridge', 'Voyatouch');
insert into NEW_TABLE (id, first_name, app_name) values (766, 'Bear, american black', 'Job');
insert into NEW_TABLE (id, first_name, app_name) values (767, 'Wallaby, euro', 'Alphazap');
insert into NEW_TABLE (id, first_name, app_name) values (768, 'Lizard, mexican beaded', 'Pannier');
insert into NEW_TABLE (id, first_name, app_name) values (769, 'Impala', 'Aerified');
insert into NEW_TABLE (id, first_name, app_name) values (770, 'Dolphin, common', 'Viva');
insert into NEW_TABLE (id, first_name, app_name) values (771, 'Cat, european wild', 'Viva');
insert into NEW_TABLE (id, first_name, app_name) values (772, 'Spider, wolf', 'Cookley');
insert into NEW_TABLE (id, first_name, app_name) values (773, 'Wallaby, dama', 'Y-find');
insert into NEW_TABLE (id, first_name, app_name) values (774, 'Black-cheeked waxbill', 'Bitwolf');
insert into NEW_TABLE (id, first_name, app_name) values (775, 'Malabar squirrel', 'Lotstring');
insert into NEW_TABLE (id, first_name, app_name) values (776, 'Cat, jungle', 'Konklab');
insert into NEW_TABLE (id, first_name, app_name) values (777, 'Striped dolphin', 'Sonair');
insert into NEW_TABLE (id, first_name, app_name) values (778, 'Crab (unidentified)', 'Flowdesk');
insert into NEW_TABLE (id, first_name, app_name) values (779, 'Wattled crane', 'It');
insert into NEW_TABLE (id, first_name, app_name) values (780, 'Monitor lizard (unidentified)', 'Flexidy');
insert into NEW_TABLE (id, first_name, app_name) values (781, 'Common wolf', 'Konklab');
insert into NEW_TABLE (id, first_name, app_name) values (782, 'Whale, killer', 'Viva');
insert into NEW_TABLE (id, first_name, app_name) values (783, 'Bleeding heart monkey', 'Bamity');
insert into NEW_TABLE (id, first_name, app_name) values (784, 'Sable antelope', 'Duobam');
insert into NEW_TABLE (id, first_name, app_name) values (785, 'Squirrel, uinta ground', 'Regrant');
insert into NEW_TABLE (id, first_name, app_name) values (786, 'Goose, knob-nosed', 'Wrapsafe');
insert into NEW_TABLE (id, first_name, app_name) values (787, 'Southern right whale', 'Tampflex');
insert into NEW_TABLE (id, first_name, app_name) values (788, 'Collared peccary', 'Job');
insert into NEW_TABLE (id, first_name, app_name) values (789, 'Potoroo', 'Sonair');
insert into NEW_TABLE (id, first_name, app_name) values (790, 'Eastern indigo snake', 'Redhold');
insert into NEW_TABLE (id, first_name, app_name) values (791, 'Black rhinoceros', 'Subin');
insert into NEW_TABLE (id, first_name, app_name) values (792, 'Goose, egyptian', 'Vagram');
insert into NEW_TABLE (id, first_name, app_name) values (793, 'Kalahari scrub robin', 'Opela');
insert into NEW_TABLE (id, first_name, app_name) values (794, 'Common zebra', 'Opela');
insert into NEW_TABLE (id, first_name, app_name) values (795, 'Red-headed woodpecker', 'Y-Solowarm');
insert into NEW_TABLE (id, first_name, app_name) values (796, 'Indian star tortoise', 'Matsoft');
insert into NEW_TABLE (id, first_name, app_name) values (797, 'Macaw, green-winged', 'Pannier');
insert into NEW_TABLE (id, first_name, app_name) values (798, 'Baboon, olive', 'Bitwolf');
insert into NEW_TABLE (id, first_name, app_name) values (799, 'Chital', 'Voltsillam');
insert into NEW_TABLE (id, first_name, app_name) values (800, 'Snake, buttermilk', 'Matsoft');
insert into NEW_TABLE (id, first_name, app_name) values (801, 'Egret, snowy', 'Zaam-Dox');
insert into NEW_TABLE (id, first_name, app_name) values (802, 'Long-tailed spotted cat', 'Konklab');
insert into NEW_TABLE (id, first_name, app_name) values (803, 'Bear, black', 'Treeflex');
insert into NEW_TABLE (id, first_name, app_name) values (804, 'Nilgai', 'Temp');
insert into NEW_TABLE (id, first_name, app_name) values (805, 'Tawny eagle', 'Tampflex');
insert into NEW_TABLE (id, first_name, app_name) values (806, 'Langur, common', 'Fintone');
insert into NEW_TABLE (id, first_name, app_name) values (807, 'Macaw, red and blue', 'Regrant');
insert into NEW_TABLE (id, first_name, app_name) values (808, 'African skink', 'Regrant');
insert into NEW_TABLE (id, first_name, app_name) values (809, 'Fork-tailed drongo', 'Zamit');
insert into NEW_TABLE (id, first_name, app_name) values (810, 'Turtle, eastern box', 'Tin');
insert into NEW_TABLE (id, first_name, app_name) values (811, 'Blackbird, red-winged', 'Ronstring');
insert into NEW_TABLE (id, first_name, app_name) values (812, 'Nilgai', 'Daltfresh');
insert into NEW_TABLE (id, first_name, app_name) values (813, 'Red hartebeest', 'Zamit');
insert into NEW_TABLE (id, first_name, app_name) values (814, 'Kangaroo, jungle', 'Domainer');
insert into NEW_TABLE (id, first_name, app_name) values (815, 'Ass, asiatic wild', 'Aerified');
insert into NEW_TABLE (id, first_name, app_name) values (816, 'Kiskadee, great', 'Quo Lux');
insert into NEW_TABLE (id, first_name, app_name) values (817, 'Indian star tortoise', 'Job');
insert into NEW_TABLE (id, first_name, app_name) values (818, 'Campo flicker', 'Sonsing');
insert into NEW_TABLE (id, first_name, app_name) values (819, 'Marshbird, brown and yellow', 'Veribet');
insert into NEW_TABLE (id, first_name, app_name) values (820, 'Chital', 'Treeflex');
insert into NEW_TABLE (id, first_name, app_name) values (821, 'Tapir, brazilian', 'Alphazap');
insert into NEW_TABLE (id, first_name, app_name) values (822, 'Bat, asian false vampire', 'Fix San');
insert into NEW_TABLE (id, first_name, app_name) values (823, 'American bison', 'Pannier');
insert into NEW_TABLE (id, first_name, app_name) values (824, 'Lorikeet, scaly-breasted', 'Holdlamis');
insert into NEW_TABLE (id, first_name, app_name) values (825, 'American crow', 'Overhold');
insert into NEW_TABLE (id, first_name, app_name) values (826, 'Gelada baboon', 'Solarbreeze');
insert into NEW_TABLE (id, first_name, app_name) values (827, 'Boa, columbian rainbow', 'Domainer');
insert into NEW_TABLE (id, first_name, app_name) values (828, 'Anteater, australian spiny', 'Konklab');
insert into NEW_TABLE (id, first_name, app_name) values (829, 'Deer, barasingha', 'Gembucket');
insert into NEW_TABLE (id, first_name, app_name) values (830, 'Turkey, wild', 'Domainer');
insert into NEW_TABLE (id, first_name, app_name) values (831, 'Heron, striated', 'Cardify');
insert into NEW_TABLE (id, first_name, app_name) values (832, 'Chimpanzee', 'Ventosanzap');
insert into NEW_TABLE (id, first_name, app_name) values (833, 'Amazon parrot (unidentified)', 'Asoka');
insert into NEW_TABLE (id, first_name, app_name) values (834, 'Devil, tasmanian', 'Tempsoft');
insert into NEW_TABLE (id, first_name, app_name) values (835, 'Snowy owl', 'Bamity');
insert into NEW_TABLE (id, first_name, app_name) values (836, 'Possum, golden brush-tailed', 'Lotlux');
insert into NEW_TABLE (id, first_name, app_name) values (837, 'Greater flamingo', 'Tampflex');
insert into NEW_TABLE (id, first_name, app_name) values (838, 'Defassa waterbuck', 'Zaam-Dox');
insert into NEW_TABLE (id, first_name, app_name) values (839, 'Snowy egret', 'Flexidy');
insert into NEW_TABLE (id, first_name, app_name) values (840, 'Constrictor, eastern boa', 'Opela');
insert into NEW_TABLE (id, first_name, app_name) values (841, 'Sage hen', 'Voltsillam');
insert into NEW_TABLE (id, first_name, app_name) values (842, 'South American puma', 'Voyatouch');
insert into NEW_TABLE (id, first_name, app_name) values (843, 'Langur, hanuman', 'Bytecard');
insert into NEW_TABLE (id, first_name, app_name) values (844, 'Blue-tongued skink', 'Cardguard');
insert into NEW_TABLE (id, first_name, app_name) values (845, 'Dove, ring', 'Domainer');
insert into NEW_TABLE (id, first_name, app_name) values (846, 'Rainbow lory', 'Regrant');
insert into NEW_TABLE (id, first_name, app_name) values (847, 'Pelican, australian', 'Transcof');
insert into NEW_TABLE (id, first_name, app_name) values (848, 'Northern phalarope', 'Tin');
insert into NEW_TABLE (id, first_name, app_name) values (849, 'Goldeneye, common', 'Y-Solowarm');
insert into NEW_TABLE (id, first_name, app_name) values (850, 'Black-tailed deer', 'Trippledex');
insert into NEW_TABLE (id, first_name, app_name) values (851, 'Sloth, hoffman''s', 'Holdlamis');
insert into NEW_TABLE (id, first_name, app_name) values (852, 'Sarus crane', 'Matsoft');
insert into NEW_TABLE (id, first_name, app_name) values (853, 'Falcon, peregrine', 'Konklux');
insert into NEW_TABLE (id, first_name, app_name) values (854, 'Shrike, common boubou', 'Regrant');
insert into NEW_TABLE (id, first_name, app_name) values (855, 'Bleu, blue-breasted cordon', 'Duobam');
insert into NEW_TABLE (id, first_name, app_name) values (856, 'Egret, cattle', 'Konklux');
insert into NEW_TABLE (id, first_name, app_name) values (857, 'Black-backed magpie', 'Matsoft');
insert into NEW_TABLE (id, first_name, app_name) values (858, 'Blue waxbill', 'Kanlam');
insert into NEW_TABLE (id, first_name, app_name) values (859, 'Kookaburra, laughing', 'Namfix');
insert into NEW_TABLE (id, first_name, app_name) values (860, 'Francolin, swainson''s', 'Mat Lam Tam');
insert into NEW_TABLE (id, first_name, app_name) values (861, 'Langur, hanuman', 'Daltfresh');
insert into NEW_TABLE (id, first_name, app_name) values (862, 'White-nosed coatimundi', 'Zaam-Dox');
insert into NEW_TABLE (id, first_name, app_name) values (863, 'Cape wild cat', 'Mat Lam Tam');
insert into NEW_TABLE (id, first_name, app_name) values (864, 'Vulture, egyptian', 'Veribet');
insert into NEW_TABLE (id, first_name, app_name) values (865, 'Deer, barasingha', 'Tin');
insert into NEW_TABLE (id, first_name, app_name) values (866, 'Verreaux''s sifaka', 'Cardify');
insert into NEW_TABLE (id, first_name, app_name) values (867, 'Flamingo, greater', 'Keylex');
insert into NEW_TABLE (id, first_name, app_name) values (868, 'Steenbuck', 'Alphazap');
insert into NEW_TABLE (id, first_name, app_name) values (869, 'Whale, baleen', 'Bamity');
insert into NEW_TABLE (id, first_name, app_name) values (870, 'Squirrel, smith''s bush', 'Prodder');
insert into NEW_TABLE (id, first_name, app_name) values (871, 'Bulbul, black-fronted', 'Andalax');
insert into NEW_TABLE (id, first_name, app_name) values (872, 'Wolf, timber', 'Zoolab');
insert into NEW_TABLE (id, first_name, app_name) values (873, 'Turtle (unidentified)', 'Bitchip');
insert into NEW_TABLE (id, first_name, app_name) values (874, 'Heron, little', 'Solarbreeze');
insert into NEW_TABLE (id, first_name, app_name) values (875, 'Fox, silver-backed', 'Sub-Ex');
insert into NEW_TABLE (id, first_name, app_name) values (876, 'Heron, boat-billed', 'Ventosanzap');
insert into NEW_TABLE (id, first_name, app_name) values (877, 'Iguana, land', 'Wrapsafe');
insert into NEW_TABLE (id, first_name, app_name) values (878, 'Indian jackal', 'Voltsillam');
insert into NEW_TABLE (id, first_name, app_name) values (879, 'Stork, marabou', 'Cookley');
insert into NEW_TABLE (id, first_name, app_name) values (880, 'Zebra, plains', 'Sub-Ex');
insert into NEW_TABLE (id, first_name, app_name) values (881, 'Guerza', 'Toughjoyfax');
insert into NEW_TABLE (id, first_name, app_name) values (882, 'Brown brocket', 'Y-Solowarm');
insert into NEW_TABLE (id, first_name, app_name) values (883, 'Blue-breasted cordon bleu', 'Tampflex');
insert into NEW_TABLE (id, first_name, app_name) values (884, 'Indian peacock', 'Bitchip');
insert into NEW_TABLE (id, first_name, app_name) values (885, 'Marten, american', 'Stim');
insert into NEW_TABLE (id, first_name, app_name) values (886, 'Turaco, violet-crested', 'Asoka');
insert into NEW_TABLE (id, first_name, app_name) values (887, 'Dama wallaby', 'Zaam-Dox');
insert into NEW_TABLE (id, first_name, app_name) values (888, 'Sociable weaver', 'Konklux');
insert into NEW_TABLE (id, first_name, app_name) values (889, 'Zorro, common', 'Sonair');
insert into NEW_TABLE (id, first_name, app_name) values (890, 'Black-faced kangaroo', 'Ventosanzap');
insert into NEW_TABLE (id, first_name, app_name) values (891, 'Burmese brown mountain tortoise', 'Subin');
insert into NEW_TABLE (id, first_name, app_name) values (892, 'Screamer, southern', 'Tresom');
insert into NEW_TABLE (id, first_name, app_name) values (893, 'Bettong, brush-tailed', 'Keylex');
insert into NEW_TABLE (id, first_name, app_name) values (894, 'Shark, blue', 'Vagram');
insert into NEW_TABLE (id, first_name, app_name) values (895, 'Vulture, black', 'Asoka');
insert into NEW_TABLE (id, first_name, app_name) values (896, 'Heron, little', 'Zontrax');
insert into NEW_TABLE (id, first_name, app_name) values (897, 'Dog, black-tailed prairie', 'Quo Lux');
insert into NEW_TABLE (id, first_name, app_name) values (898, 'Bee-eater (unidentified)', 'Namfix');
insert into NEW_TABLE (id, first_name, app_name) values (899, 'Raven, cape', 'Voyatouch');
insert into NEW_TABLE (id, first_name, app_name) values (900, 'Yellow-necked spurfowl', 'Zaam-Dox');
insert into NEW_TABLE (id, first_name, app_name) values (901, 'Shark, blue', 'Opela');
insert into NEW_TABLE (id, first_name, app_name) values (902, 'Hedgehog, south african', 'Tin');
insert into NEW_TABLE (id, first_name, app_name) values (903, 'African ground squirrel (unidentified)', 'Gembucket');
insert into NEW_TABLE (id, first_name, app_name) values (904, 'Pied crow', 'Kanlam');
insert into NEW_TABLE (id, first_name, app_name) values (905, 'Yellow-brown sungazer', 'Temp');
insert into NEW_TABLE (id, first_name, app_name) values (906, 'Sage hen', 'Quo Lux');
insert into NEW_TABLE (id, first_name, app_name) values (907, 'Coke''s hartebeest', 'Lotlux');
insert into NEW_TABLE (id, first_name, app_name) values (908, 'Galapagos penguin', 'Home Ing');
insert into NEW_TABLE (id, first_name, app_name) values (909, 'Galapagos albatross', 'Daltfresh');
insert into NEW_TABLE (id, first_name, app_name) values (910, 'Steenbok', 'Biodex');
insert into NEW_TABLE (id, first_name, app_name) values (911, 'Cobra, egyptian', 'Toughjoyfax');
insert into NEW_TABLE (id, first_name, app_name) values (912, 'Phalarope, grey', 'Overhold');
insert into NEW_TABLE (id, first_name, app_name) values (913, 'Rhea, gray', 'Bigtax');
insert into NEW_TABLE (id, first_name, app_name) values (914, 'Eurasian hoopoe', 'Tresom');
insert into NEW_TABLE (id, first_name, app_name) values (915, 'Arboral spiny rat', 'Opela');
insert into NEW_TABLE (id, first_name, app_name) values (916, 'Crab, sally lightfoot', 'Sub-Ex');
insert into NEW_TABLE (id, first_name, app_name) values (917, 'Snake, green vine', 'Bamity');
insert into NEW_TABLE (id, first_name, app_name) values (918, 'Vulture, white-headed', 'Rank');
insert into NEW_TABLE (id, first_name, app_name) values (919, 'Spotted deer', 'Alpha');
insert into NEW_TABLE (id, first_name, app_name) values (920, 'North American beaver', 'Cardify');
insert into NEW_TABLE (id, first_name, app_name) values (921, 'Trumpeter, dark-winged', 'Namfix');
insert into NEW_TABLE (id, first_name, app_name) values (922, 'Skimmer, four-spotted', 'Stronghold');
insert into NEW_TABLE (id, first_name, app_name) values (923, 'Eastern white pelican', 'Alphazap');
insert into NEW_TABLE (id, first_name, app_name) values (924, 'Snowy owl', 'Andalax');
insert into NEW_TABLE (id, first_name, app_name) values (925, 'Constrictor, eastern boa', 'It');
insert into NEW_TABLE (id, first_name, app_name) values (926, 'Dove, galapagos', 'Fix San');
insert into NEW_TABLE (id, first_name, app_name) values (927, 'Black-tailed tree creeper', 'Hatity');
insert into NEW_TABLE (id, first_name, app_name) values (928, 'Long-finned pilot whale', 'Sonsing');
insert into NEW_TABLE (id, first_name, app_name) values (929, 'Pine siskin', 'Bigtax');
insert into NEW_TABLE (id, first_name, app_name) values (930, 'Red-necked phalarope', 'Redhold');
insert into NEW_TABLE (id, first_name, app_name) values (931, 'Goose, cape barren', 'Bamity');
insert into NEW_TABLE (id, first_name, app_name) values (932, 'Paca', 'Tempsoft');
insert into NEW_TABLE (id, first_name, app_name) values (933, 'Dassie', 'Konklab');
insert into NEW_TABLE (id, first_name, app_name) values (934, 'Penguin, little blue', 'Ventosanzap');
insert into NEW_TABLE (id, first_name, app_name) values (935, 'Raven, white-necked', 'Duobam');
insert into NEW_TABLE (id, first_name, app_name) values (936, 'Dolphin, common', 'Alphazap');
insert into NEW_TABLE (id, first_name, app_name) values (937, 'Parrot, hawk-headed', 'Quo Lux');
insert into NEW_TABLE (id, first_name, app_name) values (938, 'Fox, cape', 'Fix San');
insert into NEW_TABLE (id, first_name, app_name) values (939, 'Duck, comb', 'Flexidy');
insert into NEW_TABLE (id, first_name, app_name) values (940, 'Adouri (unidentified)', 'Zontrax');
insert into NEW_TABLE (id, first_name, app_name) values (941, 'Rock dove', 'Job');
insert into NEW_TABLE (id, first_name, app_name) values (942, 'Monkey, vervet', 'Span');
insert into NEW_TABLE (id, first_name, app_name) values (943, 'King vulture', 'Toughjoyfax');
insert into NEW_TABLE (id, first_name, app_name) values (944, 'Numbat', 'Temp');
insert into NEW_TABLE (id, first_name, app_name) values (945, 'Osprey', 'Zoolab');
insert into NEW_TABLE (id, first_name, app_name) values (946, 'Cobra, egyptian', 'Asoka');
insert into NEW_TABLE (id, first_name, app_name) values (947, 'Otter, african clawless', 'Bigtax');
insert into NEW_TABLE (id, first_name, app_name) values (948, 'Olive baboon', 'Ronstring');
insert into NEW_TABLE (id, first_name, app_name) values (949, 'Komodo dragon', 'Otcom');
insert into NEW_TABLE (id, first_name, app_name) values (950, 'Burchell''s gonolek', 'Zamit');
insert into NEW_TABLE (id, first_name, app_name) values (951, 'Fox, north american red', 'Solarbreeze');
insert into NEW_TABLE (id, first_name, app_name) values (952, 'Crane, brolga', 'Sub-Ex');
insert into NEW_TABLE (id, first_name, app_name) values (953, 'Stork, white', 'Y-find');
insert into NEW_TABLE (id, first_name, app_name) values (954, 'Bandicoot, long-nosed', 'It');
insert into NEW_TABLE (id, first_name, app_name) values (955, 'Timber wolf', 'Zamit');
insert into NEW_TABLE (id, first_name, app_name) values (956, 'Rattlesnake, eastern diamondback', 'Matsoft');
insert into NEW_TABLE (id, first_name, app_name) values (957, 'Cat, african wild', 'Zoolab');
insert into NEW_TABLE (id, first_name, app_name) values (958, 'Elk, Wapiti', 'Voyatouch');
insert into NEW_TABLE (id, first_name, app_name) values (959, 'Reedbuck, bohor', 'Stringtough');
insert into NEW_TABLE (id, first_name, app_name) values (960, 'Common grenadier', 'Bigtax');
insert into NEW_TABLE (id, first_name, app_name) values (961, 'Brown capuchin', 'Wrapsafe');
insert into NEW_TABLE (id, first_name, app_name) values (962, 'Bison, american', 'Toughjoyfax');
insert into NEW_TABLE (id, first_name, app_name) values (963, 'Monitor lizard (unidentified)', 'Sonair');
insert into NEW_TABLE (id, first_name, app_name) values (964, 'White-necked stork', 'Ventosanzap');
insert into NEW_TABLE (id, first_name, app_name) values (965, 'Herring gull', 'Zoolab');
insert into NEW_TABLE (id, first_name, app_name) values (966, 'Yellow-throated sandgrouse', 'Andalax');
insert into NEW_TABLE (id, first_name, app_name) values (967, 'Cormorant, large', 'Solarbreeze');
insert into NEW_TABLE (id, first_name, app_name) values (968, 'Topi', 'Gembucket');
insert into NEW_TABLE (id, first_name, app_name) values (969, 'Bleeding heart monkey', 'Greenlam');
insert into NEW_TABLE (id, first_name, app_name) values (970, 'Sockeye salmon', 'Lotlux');
insert into NEW_TABLE (id, first_name, app_name) values (971, 'Lesser masked weaver', 'Domainer');
insert into NEW_TABLE (id, first_name, app_name) values (972, 'African wild cat', 'Cardguard');
insert into NEW_TABLE (id, first_name, app_name) values (973, 'Southern lapwing', 'Trippledex');
insert into NEW_TABLE (id, first_name, app_name) values (974, 'Quail, gambel''s', 'Kanlam');
insert into NEW_TABLE (id, first_name, app_name) values (975, 'Great white pelican', 'Regrant');
insert into NEW_TABLE (id, first_name, app_name) values (976, 'Beaver, european', 'Sonsing');
insert into NEW_TABLE (id, first_name, app_name) values (977, 'Mississippi alligator', 'Cookley');
insert into NEW_TABLE (id, first_name, app_name) values (978, 'Badger, american', 'Biodex');
insert into NEW_TABLE (id, first_name, app_name) values (979, 'Elk, Wapiti', 'Solarbreeze');
insert into NEW_TABLE (id, first_name, app_name) values (980, 'Bulbul, black-eyed', 'Temp');
insert into NEW_TABLE (id, first_name, app_name) values (981, 'Fisher', 'Zamit');
insert into NEW_TABLE (id, first_name, app_name) values (982, 'Scaly-breasted lorikeet', 'Zaam-Dox');
insert into NEW_TABLE (id, first_name, app_name) values (983, 'Skunk, western spotted', 'Sonair');
insert into NEW_TABLE (id, first_name, app_name) values (984, 'Red hartebeest', 'Veribet');
insert into NEW_TABLE (id, first_name, app_name) values (985, 'River wallaby', 'Flexidy');
insert into NEW_TABLE (id, first_name, app_name) values (986, 'Goose, andean', 'Wrapsafe');
insert into NEW_TABLE (id, first_name, app_name) values (987, 'Asian water dragon', 'Tresom');
insert into NEW_TABLE (id, first_name, app_name) values (988, 'Royal tern', 'Span');
insert into NEW_TABLE (id, first_name, app_name) values (989, 'Skink, african', 'Trippledex');
insert into NEW_TABLE (id, first_name, app_name) values (990, 'North American porcupine', 'Wrapsafe');
insert into NEW_TABLE (id, first_name, app_name) values (991, 'Ringtail, common', 'Opela');
insert into NEW_TABLE (id, first_name, app_name) values (992, 'Wagtail, african pied', 'Cookley');
insert into NEW_TABLE (id, first_name, app_name) values (993, 'Lizard, desert spiny', 'Duobam');
insert into NEW_TABLE (id, first_name, app_name) values (994, 'Boat-billed heron', 'Bytecard');
insert into NEW_TABLE (id, first_name, app_name) values (995, 'Gecko, bent-toed', 'Gembucket');
insert into NEW_TABLE (id, first_name, app_name) values (996, 'Tortoise, asian foreset', 'Namfix');
insert into NEW_TABLE (id, first_name, app_name) values (997, 'Fox, asian red', 'Pannier');
insert into NEW_TABLE (id, first_name, app_name) values (998, 'Ibis, puna', 'Toughjoyfax');
insert into NEW_TABLE (id, first_name, app_name) values (999, 'Savannah deer (unidentified)', 'Wrapsafe');
insert into NEW_TABLE (id, first_name, app_name) values (1000, 'Tortoise, desert', 'Zoolab');
